package paneles;

public class pnl_footer extends javax.swing.JPanel {

    public pnl_footer() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lbl_url = new javax.swing.JLabel();

        setBackground(new java.awt.Color(51, 51, 51));
        setPreferredSize(new java.awt.Dimension(120, 80));
        setLayout(new java.awt.GridLayout(1, 0));

        lbl_url.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        lbl_url.setForeground(new java.awt.Color(255, 255, 255));
        lbl_url.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl_url.setText("www.saitolab.com");
        add(lbl_url);
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel lbl_url;
    // End of variables declaration//GEN-END:variables
}
