package paneles;

import consultas.ConsulOperario;
import clases.Operario;

public class pnl_sesionde extends javax.swing.JPanel {

    public pnl_sesionde() {
        initComponents();
        Mostrar();
    }
    
    public static void Mostrar(){
        //¿Quien esta haciendo la sesion?
        Operario usuario = ConsulOperario.USUARIO;
        lbl_usuario.setText(usuario.getNombre() + " " + usuario.getAp_paterno());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lbl_sesionde = new javax.swing.JLabel();
        lbl_usuario = new javax.swing.JLabel();

        setOpaque(false);
        setPreferredSize(new java.awt.Dimension(120, 80));

        lbl_sesionde.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lbl_sesionde.setText("Sesion de:");

        lbl_usuario.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        lbl_usuario.setText("...");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lbl_sesionde, javax.swing.GroupLayout.DEFAULT_SIZE, 100, Short.MAX_VALUE)
                    .addComponent(lbl_usuario, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lbl_sesionde, javax.swing.GroupLayout.DEFAULT_SIZE, 29, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lbl_usuario, javax.swing.GroupLayout.DEFAULT_SIZE, 23, Short.MAX_VALUE)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel lbl_sesionde;
    private static javax.swing.JLabel lbl_usuario;
    // End of variables declaration//GEN-END:variables
}
