package ventanas;

import clases.Area;
import consultas.ConsulArea;
import consultas.ConsulMaquinaria;
import javax.swing.JOptionPane;
import paneles.*;

public class frm_areas extends javax.swing.JFrame {

    public static String ventana = "";
    private String accion = "guardar";

    public frm_areas() {
        initComponents();

        //Paneles
        pnl_sesion_info.add(new pnl_sesionde());
        pnl_pie.add(new pnl_footer());

        //Mostrar las areas
        Mostrar();
    }

    private void Inhabilitar() {
        txt_nombre.setEnabled(false);
        txt_descripcion.setEnabled(false);

        txt_id_area.setText("");
        txt_nombre.setText("");
        txt_descripcion.setText("");

        btn_guardar.setEnabled(false);
        btn_eliminar.setEnabled(false);
    }

    private void Habilitar() {
        txt_nombre.setEnabled(true);
        txt_descripcion.setEnabled(true);

        txt_id_area.setText("");
        txt_nombre.setText("");
        txt_descripcion.setText("");

        btn_guardar.setEnabled(true);
        btn_eliminar.setEnabled(false);
    }

    private void Mostrar() {
        tab_areas.setModel(new ConsulArea().mostrar(txt_buscar.getText()));
        OcultarColumnas();
        lbl_num_registros.setText("Número de areas: " + ConsulArea.num_registros);
    }

    private void OcultarColumnas() {
        int[] columnas = {0};
        for (int columna : columnas) {
            tab_areas.getColumnModel().getColumn(columna).setMaxWidth(0);
            tab_areas.getColumnModel().getColumn(columna).setMinWidth(0);
            tab_areas.getColumnModel().getColumn(columna).setPreferredWidth(0);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnl_cabecera = new javax.swing.JPanel();
        lbl_titulo = new javax.swing.JLabel();
        pnl_sesion_info = new javax.swing.JPanel();
        pnl_contenido = new javax.swing.JPanel();
        pnl_controles = new javax.swing.JPanel();
        txt_id_area = new javax.swing.JTextField();
        lbl_nombre = new javax.swing.JLabel();
        txt_nombre = new javax.swing.JTextField();
        lbl_descripcion = new javax.swing.JLabel();
        jScrollPane_descripcion = new javax.swing.JScrollPane();
        txt_descripcion = new javax.swing.JTextArea();
        pnl_botones = new javax.swing.JPanel();
        btn_nuevo = new javax.swing.JButton();
        btn_guardar = new javax.swing.JButton();
        btn_eliminar = new javax.swing.JButton();
        pnl_tabla = new javax.swing.JPanel();
        lbl_buscar_area = new javax.swing.JLabel();
        txt_buscar = new javax.swing.JTextField();
        btn_buscar = new javax.swing.JButton();
        jScrollPane_tabla = new javax.swing.JScrollPane();
        tab_areas = new javax.swing.JTable();
        lbl_num_registros = new javax.swing.JLabel();
        pnl_pie = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Areas de trabajo");
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setSize(new java.awt.Dimension(1280, 640));
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosed(java.awt.event.WindowEvent evt) {
                formWindowClosed(evt);
            }
        });
        getContentPane().setLayout(new java.awt.BorderLayout(0, 4));

        pnl_cabecera.setBackground(new java.awt.Color(179, 57, 57));
        pnl_cabecera.setPreferredSize(new java.awt.Dimension(1280, 80));
        pnl_cabecera.setLayout(new java.awt.BorderLayout());

        lbl_titulo.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        lbl_titulo.setForeground(new java.awt.Color(255, 255, 255));
        lbl_titulo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl_titulo.setText("GESTOR DE AREAS DE TRABAJO");
        pnl_cabecera.add(lbl_titulo, java.awt.BorderLayout.CENTER);

        pnl_sesion_info.setBackground(new java.awt.Color(255, 82, 82));
        pnl_sesion_info.setPreferredSize(new java.awt.Dimension(120, 80));
        pnl_sesion_info.setLayout(new java.awt.GridLayout(1, 0));
        pnl_cabecera.add(pnl_sesion_info, java.awt.BorderLayout.LINE_END);

        getContentPane().add(pnl_cabecera, java.awt.BorderLayout.PAGE_START);

        pnl_contenido.setBackground(new java.awt.Color(204, 204, 204));
        pnl_contenido.setLayout(new java.awt.GridLayout(1, 0, 4, 4));

        pnl_controles.setBackground(new java.awt.Color(255, 255, 255));

        txt_id_area.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txt_id_area.setEnabled(false);

        lbl_nombre.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lbl_nombre.setText("Nombre del area:");

        txt_nombre.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txt_nombre.setEnabled(false);

        lbl_descripcion.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lbl_descripcion.setText("Descripción:");

        txt_descripcion.setColumns(20);
        txt_descripcion.setLineWrap(true);
        txt_descripcion.setRows(5);
        txt_descripcion.setEnabled(false);
        jScrollPane_descripcion.setViewportView(txt_descripcion);

        pnl_botones.setLayout(new java.awt.GridLayout(1, 0, 4, 4));

        btn_nuevo.setBackground(new java.awt.Color(204, 204, 204));
        btn_nuevo.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        btn_nuevo.setText("Nuevo");
        btn_nuevo.setContentAreaFilled(false);
        btn_nuevo.setOpaque(true);
        btn_nuevo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_nuevoActionPerformed(evt);
            }
        });
        pnl_botones.add(btn_nuevo);

        btn_guardar.setBackground(new java.awt.Color(204, 204, 204));
        btn_guardar.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        btn_guardar.setText("Guardar");
        btn_guardar.setContentAreaFilled(false);
        btn_guardar.setEnabled(false);
        btn_guardar.setOpaque(true);
        btn_guardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_guardarActionPerformed(evt);
            }
        });
        pnl_botones.add(btn_guardar);

        btn_eliminar.setBackground(new java.awt.Color(204, 204, 204));
        btn_eliminar.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        btn_eliminar.setText("Eliminar");
        btn_eliminar.setContentAreaFilled(false);
        btn_eliminar.setEnabled(false);
        btn_eliminar.setOpaque(true);
        btn_eliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_eliminarActionPerformed(evt);
            }
        });
        pnl_botones.add(btn_eliminar);

        javax.swing.GroupLayout pnl_controlesLayout = new javax.swing.GroupLayout(pnl_controles);
        pnl_controles.setLayout(pnl_controlesLayout);
        pnl_controlesLayout.setHorizontalGroup(
            pnl_controlesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnl_controlesLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnl_controlesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(pnl_botones, javax.swing.GroupLayout.DEFAULT_SIZE, 618, Short.MAX_VALUE)
                    .addGroup(pnl_controlesLayout.createSequentialGroup()
                        .addGroup(pnl_controlesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lbl_nombre)
                            .addComponent(lbl_descripcion))
                        .addGap(18, 18, 18)
                        .addGroup(pnl_controlesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txt_id_area, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txt_nombre)
                            .addComponent(jScrollPane_descripcion))))
                .addContainerGap())
        );
        pnl_controlesLayout.setVerticalGroup(
            pnl_controlesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnl_controlesLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(txt_id_area, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnl_controlesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txt_nombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbl_nombre))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnl_controlesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnl_controlesLayout.createSequentialGroup()
                        .addComponent(jScrollPane_descripcion, javax.swing.GroupLayout.DEFAULT_SIZE, 326, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(pnl_botones, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(pnl_controlesLayout.createSequentialGroup()
                        .addComponent(lbl_descripcion)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );

        pnl_contenido.add(pnl_controles);

        pnl_tabla.setBackground(new java.awt.Color(255, 255, 255));

        lbl_buscar_area.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lbl_buscar_area.setText("Areas de trabajo:");

        btn_buscar.setText("Buscar");
        btn_buscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_buscarActionPerformed(evt);
            }
        });

        tab_areas.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tab_areas.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tab_areasMouseClicked(evt);
            }
        });
        jScrollPane_tabla.setViewportView(tab_areas);

        lbl_num_registros.setText("Número de areas:");

        javax.swing.GroupLayout pnl_tablaLayout = new javax.swing.GroupLayout(pnl_tabla);
        pnl_tabla.setLayout(pnl_tablaLayout);
        pnl_tablaLayout.setHorizontalGroup(
            pnl_tablaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnl_tablaLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnl_tablaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane_tabla, javax.swing.GroupLayout.DEFAULT_SIZE, 618, Short.MAX_VALUE)
                    .addGroup(pnl_tablaLayout.createSequentialGroup()
                        .addComponent(lbl_buscar_area)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txt_buscar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btn_buscar))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnl_tablaLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(lbl_num_registros)))
                .addContainerGap())
        );
        pnl_tablaLayout.setVerticalGroup(
            pnl_tablaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnl_tablaLayout.createSequentialGroup()
                .addGap(13, 13, 13)
                .addGroup(pnl_tablaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbl_buscar_area)
                    .addComponent(txt_buscar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_buscar))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane_tabla, javax.swing.GroupLayout.DEFAULT_SIZE, 439, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lbl_num_registros)
                .addContainerGap())
        );

        pnl_contenido.add(pnl_tabla);

        getContentPane().add(pnl_contenido, java.awt.BorderLayout.CENTER);

        pnl_pie.setBackground(new java.awt.Color(82, 190, 128));
        pnl_pie.setPreferredSize(new java.awt.Dimension(1280, 40));
        pnl_pie.setLayout(new java.awt.BorderLayout());
        getContentPane().add(pnl_pie, java.awt.BorderLayout.SOUTH);

        setSize(new java.awt.Dimension(1296, 679));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btn_guardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_guardarActionPerformed
        //Validacion de datos
        if (txt_nombre.getText().equals("")) {
            JOptionPane.showMessageDialog(this, "Se debe ingresar un nombre para el area");
            txt_nombre.requestFocus();
            return;
        }
        if (txt_descripcion.getText().equals("")) {
            JOptionPane.showMessageDialog(this, "Se debe ingresar una descripción para el area");
            txt_descripcion.requestFocus();
            return;
        }

        //Lectura de datos
        Area dts = new Area();
        dts.setNombre(txt_nombre.getText());
        dts.setDescripcion(txt_descripcion.getText());

        //Envio de datos
        ConsulArea func = new ConsulArea();
        if (accion.equals("guardar")) {
            if (func.insertar(dts)) {
                JOptionPane.showMessageDialog(this, "Area registrada satisfactoriamente");
                Mostrar();
                Inhabilitar();
            }
        } else if (accion.equals("editar")) {
            dts.setId(Integer.parseInt(txt_id_area.getText()));
            if (func.editar(dts)) {
                JOptionPane.showMessageDialog(this, "Area editada satisfactoriamente");
                Mostrar();
                Inhabilitar();
            }
        }

    }//GEN-LAST:event_btn_guardarActionPerformed

    private void btn_eliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_eliminarActionPerformed
        if (!txt_id_area.getText().equals("")) {
            //Lectura y obtencion de datos
            Area dts = new ConsulArea().obtener(Integer.parseInt(txt_id_area.getText()));
            //El area tiene maquinarias?
            if (new ConsulMaquinaria().hayMaquinaria(dts)) {
                String msg = "Esta area no se puede eliminar\n"
                        + "Hay maquinarias registradas de esta area";
                JOptionPane.showMessageDialog(this, msg);
                return;
            }
            //Confirmacion
            int confirmacion = JOptionPane.showConfirmDialog(this, "¿Estás seguro de eliminar la maquinaria?", "Confirmar", 2);
            if (confirmacion == 0) {
                //Envio de datos
                ConsulArea func = new ConsulArea();
                if (func.eliminar(dts)) {
                    JOptionPane.showMessageDialog(this, "Area eliminada satisfactoriamente");
                    Mostrar();
                    Inhabilitar();
                }
            }
        }
    }//GEN-LAST:event_btn_eliminarActionPerformed

    private void btn_nuevoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_nuevoActionPerformed
        Habilitar();
        btn_guardar.setText("Guardar");
        accion = "guardar";
    }//GEN-LAST:event_btn_nuevoActionPerformed

    private void tab_areasMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tab_areasMouseClicked
        //Habilitacion de campos
        btn_guardar.setText("Editar");
        Habilitar();
        btn_eliminar.setEnabled(true);
        accion = "editar";

        //Rellenado de campos
        int fila = tab_areas.rowAtPoint(evt.getPoint());
        txt_id_area.setText(tab_areas.getValueAt(fila, 0).toString());
        txt_nombre.setText(tab_areas.getValueAt(fila, 1).toString());
        txt_descripcion.setText(tab_areas.getValueAt(fila, 2).toString());
    }//GEN-LAST:event_tab_areasMouseClicked

    private void btn_buscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_buscarActionPerformed
        Mostrar();
    }//GEN-LAST:event_btn_buscarActionPerformed

    private void formWindowClosed(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosed
        
        switch (ventana) {
            case "MAQ" -> {//Si lo abrió el gestionador de maquinas
                frm_maquinas.ListaAreas();
                frm_maquinas.cmb_areas.setSelectedIndex(0);
                frm_maquinas.MostrarMaquinarias();
            }
            case "MAN" -> {//Si lo abrió el manual
                frm_manual.ListaAreas();
                frm_manual.cmb_area.setSelectedIndex(0);
                frm_manual.ListaMaquinarias();
                frm_manual.cmb_maquinaria.setSelectedIndex(0);
            }
            default -> {
            }
        }
        ventana = "";
    }//GEN-LAST:event_formWindowClosed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frm_areas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frm_areas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frm_areas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frm_areas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frm_areas().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_buscar;
    private javax.swing.JButton btn_eliminar;
    private javax.swing.JButton btn_guardar;
    private javax.swing.JButton btn_nuevo;
    private javax.swing.JScrollPane jScrollPane_descripcion;
    private javax.swing.JScrollPane jScrollPane_tabla;
    private javax.swing.JLabel lbl_buscar_area;
    private javax.swing.JLabel lbl_descripcion;
    private javax.swing.JLabel lbl_nombre;
    private javax.swing.JLabel lbl_num_registros;
    private javax.swing.JLabel lbl_titulo;
    private javax.swing.JPanel pnl_botones;
    private javax.swing.JPanel pnl_cabecera;
    private javax.swing.JPanel pnl_contenido;
    private javax.swing.JPanel pnl_controles;
    private javax.swing.JPanel pnl_pie;
    private javax.swing.JPanel pnl_sesion_info;
    private javax.swing.JPanel pnl_tabla;
    private javax.swing.JTable tab_areas;
    private javax.swing.JTextField txt_buscar;
    private javax.swing.JTextArea txt_descripcion;
    private javax.swing.JTextField txt_id_area;
    private javax.swing.JTextField txt_nombre;
    // End of variables declaration//GEN-END:variables
}
