package ventanas;

import clases.Feriado;
import clases.Jornada;
import consultas.Auxiliar;
import consultas.ConsulAgenda;
import consultas.ConsulDiasLaborales;
import consultas.ConsulFeriado;
import consultas.ConsulJornada;
import java.sql.Date;
import java.util.Calendar;
import javax.swing.JOptionPane;
import paneles.*;

public class frm_dias extends javax.swing.JFrame {

    private String accionFeriado = "guardar";

    public frm_dias() {
        initComponents();

        //Paneles
        pnl_sesion_info.add(new pnl_sesionde());
        pnl_pie.add(new pnl_footer());

        //Panel dias laborales
        MostrarDiasLaborales();

        //Panel jornada
        int year = Calendar.getInstance().get(Calendar.YEAR);
        ych_anho.setValue(year);
        dtc_fecha_inicial.setDate(Auxiliar.FirstDayOfTheYear(year));
        dtc_fecha_final.setDate(Auxiliar.LastDayOfTheYear(year));

        //Panel feriados
        //Muestra las agendas
        MostrarJornadas();
        MostrarFeriados();
    }

    private void MostrarDiasLaborales() {
        boolean[] dias_laborales = new ConsulDiasLaborales().mostrar();
        chb_domingo.setSelected(dias_laborales[0]);
        chb_lunes.setSelected(dias_laborales[1]);
        chb_martes.setSelected(dias_laborales[2]);
        chb_miercoles.setSelected(dias_laborales[3]);
        chb_jueves.setSelected(dias_laborales[4]);
        chb_viernes.setSelected(dias_laborales[5]);
        chb_sabado.setSelected(dias_laborales[6]);

    }

    private void MostrarJornadas() {
        tab_jornadas.setModel(new ConsulJornada().mostrar());
    }

    private void InhabilitarFeriado() {
        dtc_fecha_feriado1.setEnabled(false);
        txt_descripcion_feriado.setEnabled(false);

        txt_id_feriado.setText("");
        txt_descripcion_feriado.setText("");

        chb_variosDias.setEnabled(false);

        chb_variosDias.setSelected(false);

        btn_guardar_feriado.setEnabled(false);
        btn_eliminar_feriado.setEnabled(false);
    }

    private void HabilitarFeriado() {
        dtc_fecha_feriado1.setEnabled(true);
        txt_descripcion_feriado.setEnabled(true);

        txt_id_feriado.setText("");
        txt_descripcion_feriado.setText("");

        chb_variosDias.setSelected(false);

        btn_guardar_feriado.setEnabled(true);
        btn_eliminar_feriado.setEnabled(false);
    }

    private void MostrarFeriados() {
        tab_feriados.setModel(new ConsulFeriado().mostrar());
        OcultarColumnasFeriado();
    }

    private void OcultarColumnasFeriado() {
        int[] columnas = {0};
        for (int columna : columnas) {
            tab_feriados.getColumnModel().getColumn(columna).setMaxWidth(0);
            tab_feriados.getColumnModel().getColumn(columna).setMinWidth(0);
            tab_feriados.getColumnModel().getColumn(columna).setPreferredWidth(0);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnl_cabecera = new javax.swing.JPanel();
        lbl_titulo = new javax.swing.JLabel();
        pnl_sesion_info = new javax.swing.JPanel();
        jtp_contenido = new javax.swing.JTabbedPane();
        pnl_dias_laborales = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        pnl_dias = new javax.swing.JPanel();
        chb_lunes = new javax.swing.JCheckBox();
        chb_martes = new javax.swing.JCheckBox();
        chb_miercoles = new javax.swing.JCheckBox();
        chb_jueves = new javax.swing.JCheckBox();
        chb_viernes = new javax.swing.JCheckBox();
        chb_sabado = new javax.swing.JCheckBox();
        chb_domingo = new javax.swing.JCheckBox();
        jLabel2 = new javax.swing.JLabel();
        btn_guardar_dias_laborales = new javax.swing.JButton();
        pnl_jornada_anual = new javax.swing.JPanel();
        lbl_anho = new javax.swing.JLabel();
        ych_anho = new com.toedter.calendar.JYearChooser();
        lbl_fecha_inicial = new javax.swing.JLabel();
        lbl_fecha_final = new javax.swing.JLabel();
        btn_guardar_jornada = new javax.swing.JButton();
        jScrollPane_tabla_jornadas = new javax.swing.JScrollPane();
        tab_jornadas = new javax.swing.JTable();
        dtc_fecha_inicial = new com.toedter.calendar.JDateChooser();
        dtc_fecha_final = new com.toedter.calendar.JDateChooser();
        btn_fecha_inicial_default = new javax.swing.JButton();
        btn_fecha_final_default = new javax.swing.JButton();
        pnl_feriados = new javax.swing.JPanel();
        txt_id_feriado = new javax.swing.JTextField();
        lbl_fecha_feriado = new javax.swing.JLabel();
        dtc_fecha_feriado1 = new com.toedter.calendar.JDateChooser();
        dtc_fecha_feriado2 = new com.toedter.calendar.JDateChooser();
        chb_variosDias = new javax.swing.JCheckBox();
        lbl_descripcion_feriado = new javax.swing.JLabel();
        txt_descripcion_feriado = new javax.swing.JTextField();
        pnl_botones = new javax.swing.JPanel();
        btn_nuevo_feriado = new javax.swing.JButton();
        btn_guardar_feriado = new javax.swing.JButton();
        btn_eliminar_feriado = new javax.swing.JButton();
        jScrollPane_tabla_feriados = new javax.swing.JScrollPane();
        tab_feriados = new javax.swing.JTable();
        pnl_pie = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Días de trabajo");
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setPreferredSize(new java.awt.Dimension(640, 640));
        setResizable(false);
        setSize(new java.awt.Dimension(640, 640));
        getContentPane().setLayout(new java.awt.BorderLayout(0, 4));

        pnl_cabecera.setBackground(new java.awt.Color(71, 71, 135));
        pnl_cabecera.setPreferredSize(new java.awt.Dimension(1280, 80));
        pnl_cabecera.setLayout(new java.awt.BorderLayout());

        lbl_titulo.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        lbl_titulo.setForeground(new java.awt.Color(255, 255, 255));
        lbl_titulo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl_titulo.setText("GESTOR DE DIAS DE TRABAJO");
        pnl_cabecera.add(lbl_titulo, java.awt.BorderLayout.CENTER);

        pnl_sesion_info.setBackground(new java.awt.Color(112, 111, 211));
        pnl_sesion_info.setPreferredSize(new java.awt.Dimension(120, 80));
        pnl_sesion_info.setLayout(new java.awt.GridLayout(1, 0));
        pnl_cabecera.add(pnl_sesion_info, java.awt.BorderLayout.LINE_END);

        getContentPane().add(pnl_cabecera, java.awt.BorderLayout.PAGE_START);

        jtp_contenido.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jtp_contenido.setOpaque(true);

        pnl_dias_laborales.setBackground(new java.awt.Color(255, 255, 255));
        pnl_dias_laborales.setLayout(new java.awt.BorderLayout());

        jLabel1.setPreferredSize(new java.awt.Dimension(40, 14));
        pnl_dias_laborales.add(jLabel1, java.awt.BorderLayout.WEST);

        pnl_dias.setLayout(new java.awt.GridLayout(0, 1, 0, 4));

        chb_lunes.setBackground(new java.awt.Color(255, 255, 255));
        chb_lunes.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        chb_lunes.setText("LUNES");
        pnl_dias.add(chb_lunes);

        chb_martes.setBackground(new java.awt.Color(255, 255, 255));
        chb_martes.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        chb_martes.setText("MARTES");
        pnl_dias.add(chb_martes);

        chb_miercoles.setBackground(new java.awt.Color(255, 255, 255));
        chb_miercoles.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        chb_miercoles.setText("MIERCOLES");
        pnl_dias.add(chb_miercoles);

        chb_jueves.setBackground(new java.awt.Color(255, 255, 255));
        chb_jueves.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        chb_jueves.setText("JUEVES");
        pnl_dias.add(chb_jueves);

        chb_viernes.setBackground(new java.awt.Color(255, 255, 255));
        chb_viernes.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        chb_viernes.setText("VIERNES");
        pnl_dias.add(chb_viernes);

        chb_sabado.setBackground(new java.awt.Color(255, 255, 255));
        chb_sabado.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        chb_sabado.setText("SABADO");
        pnl_dias.add(chb_sabado);

        chb_domingo.setBackground(new java.awt.Color(255, 255, 255));
        chb_domingo.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        chb_domingo.setText("DOMINGO");
        pnl_dias.add(chb_domingo);

        pnl_dias_laborales.add(pnl_dias, java.awt.BorderLayout.CENTER);

        jLabel2.setPreferredSize(new java.awt.Dimension(40, 14));
        pnl_dias_laborales.add(jLabel2, java.awt.BorderLayout.EAST);

        btn_guardar_dias_laborales.setBackground(new java.awt.Color(204, 204, 204));
        btn_guardar_dias_laborales.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        btn_guardar_dias_laborales.setText("Guardar");
        btn_guardar_dias_laborales.setContentAreaFilled(false);
        btn_guardar_dias_laborales.setOpaque(true);
        btn_guardar_dias_laborales.setPreferredSize(new java.awt.Dimension(129, 60));
        btn_guardar_dias_laborales.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_guardar_dias_laboralesActionPerformed(evt);
            }
        });
        pnl_dias_laborales.add(btn_guardar_dias_laborales, java.awt.BorderLayout.SOUTH);

        jtp_contenido.addTab("Días laborales", pnl_dias_laborales);

        pnl_jornada_anual.setBackground(new java.awt.Color(255, 255, 255));

        lbl_anho.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lbl_anho.setText("Año:");

        lbl_fecha_inicial.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lbl_fecha_inicial.setText("Fecha inicial:");

        lbl_fecha_final.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lbl_fecha_final.setText("Fecha final:");

        btn_guardar_jornada.setBackground(new java.awt.Color(204, 204, 204));
        btn_guardar_jornada.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btn_guardar_jornada.setText("Guardar");
        btn_guardar_jornada.setContentAreaFilled(false);
        btn_guardar_jornada.setOpaque(true);
        btn_guardar_jornada.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_guardar_jornadaActionPerformed(evt);
            }
        });

        tab_jornadas.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tab_jornadas.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tab_jornadasMouseClicked(evt);
            }
        });
        jScrollPane_tabla_jornadas.setViewportView(tab_jornadas);

        btn_fecha_inicial_default.setText("01-01");
        btn_fecha_inicial_default.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_fecha_inicial_defaultActionPerformed(evt);
            }
        });

        btn_fecha_final_default.setText("31-12");
        btn_fecha_final_default.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_fecha_final_defaultActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnl_jornada_anualLayout = new javax.swing.GroupLayout(pnl_jornada_anual);
        pnl_jornada_anual.setLayout(pnl_jornada_anualLayout);
        pnl_jornada_anualLayout.setHorizontalGroup(
            pnl_jornada_anualLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnl_jornada_anualLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnl_jornada_anualLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnl_jornada_anualLayout.createSequentialGroup()
                        .addGroup(pnl_jornada_anualLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(pnl_jornada_anualLayout.createSequentialGroup()
                                .addGroup(pnl_jornada_anualLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lbl_fecha_inicial)
                                    .addComponent(lbl_anho))
                                .addGap(18, 18, 18)
                                .addGroup(pnl_jornada_anualLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(dtc_fecha_inicial, javax.swing.GroupLayout.DEFAULT_SIZE, 107, Short.MAX_VALUE)
                                    .addComponent(ych_anho, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnl_jornada_anualLayout.createSequentialGroup()
                                .addComponent(lbl_fecha_final)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(dtc_fecha_final, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(pnl_jornada_anualLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(pnl_jornada_anualLayout.createSequentialGroup()
                                .addComponent(btn_fecha_final_default)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btn_guardar_jornada))
                            .addComponent(btn_fecha_inicial_default))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(pnl_jornada_anualLayout.createSequentialGroup()
                        .addComponent(jScrollPane_tabla_jornadas, javax.swing.GroupLayout.DEFAULT_SIZE, 615, Short.MAX_VALUE)
                        .addContainerGap())))
        );
        pnl_jornada_anualLayout.setVerticalGroup(
            pnl_jornada_anualLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnl_jornada_anualLayout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addGroup(pnl_jornada_anualLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(ych_anho, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lbl_anho, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnl_jornada_anualLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnl_jornada_anualLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(lbl_fecha_inicial, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(dtc_fecha_inicial, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(btn_fecha_inicial_default))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnl_jornada_anualLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnl_jornada_anualLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(btn_fecha_final_default)
                        .addComponent(btn_guardar_jornada))
                    .addComponent(dtc_fecha_final, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbl_fecha_final, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane_tabla_jornadas, javax.swing.GroupLayout.DEFAULT_SIZE, 366, Short.MAX_VALUE)
                .addContainerGap())
        );

        jtp_contenido.addTab("Jornada del año", pnl_jornada_anual);

        pnl_feriados.setBackground(new java.awt.Color(255, 255, 255));

        txt_id_feriado.setEnabled(false);

        lbl_fecha_feriado.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lbl_fecha_feriado.setText("Fecha(s) feriado:");

        dtc_fecha_feriado1.setEnabled(false);

        dtc_fecha_feriado2.setEnabled(false);

        chb_variosDias.setBackground(new java.awt.Color(255, 255, 255));
        chb_variosDias.setText("Varias dias");
        chb_variosDias.setEnabled(false);
        chb_variosDias.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                chb_variosDiasStateChanged(evt);
            }
        });

        lbl_descripcion_feriado.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lbl_descripcion_feriado.setText("Descripcion:");

        txt_descripcion_feriado.setEnabled(false);

        pnl_botones.setLayout(new java.awt.GridLayout(1, 0, 4, 4));

        btn_nuevo_feriado.setBackground(new java.awt.Color(204, 204, 204));
        btn_nuevo_feriado.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        btn_nuevo_feriado.setText("Nuevo");
        btn_nuevo_feriado.setContentAreaFilled(false);
        btn_nuevo_feriado.setOpaque(true);
        btn_nuevo_feriado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_nuevo_feriadoActionPerformed(evt);
            }
        });
        pnl_botones.add(btn_nuevo_feriado);

        btn_guardar_feriado.setBackground(new java.awt.Color(204, 204, 204));
        btn_guardar_feriado.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        btn_guardar_feriado.setText("Guardar");
        btn_guardar_feriado.setContentAreaFilled(false);
        btn_guardar_feriado.setEnabled(false);
        btn_guardar_feriado.setOpaque(true);
        btn_guardar_feriado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_guardar_feriadoActionPerformed(evt);
            }
        });
        pnl_botones.add(btn_guardar_feriado);

        btn_eliminar_feriado.setBackground(new java.awt.Color(204, 204, 204));
        btn_eliminar_feriado.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        btn_eliminar_feriado.setText("Eliminar");
        btn_eliminar_feriado.setContentAreaFilled(false);
        btn_eliminar_feriado.setEnabled(false);
        btn_eliminar_feriado.setOpaque(true);
        btn_eliminar_feriado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_eliminar_feriadoActionPerformed(evt);
            }
        });
        pnl_botones.add(btn_eliminar_feriado);

        tab_feriados.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tab_feriados.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tab_feriadosMouseClicked(evt);
            }
        });
        jScrollPane_tabla_feriados.setViewportView(tab_feriados);

        javax.swing.GroupLayout pnl_feriadosLayout = new javax.swing.GroupLayout(pnl_feriados);
        pnl_feriados.setLayout(pnl_feriadosLayout);
        pnl_feriadosLayout.setHorizontalGroup(
            pnl_feriadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnl_feriadosLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnl_feriadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnl_feriadosLayout.createSequentialGroup()
                        .addGroup(pnl_feriadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane_tabla_feriados, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 615, Short.MAX_VALUE)
                            .addComponent(pnl_botones, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 615, Short.MAX_VALUE)
                            .addGroup(pnl_feriadosLayout.createSequentialGroup()
                                .addComponent(lbl_descripcion_feriado)
                                .addGap(51, 51, 51)
                                .addComponent(txt_descripcion_feriado)))
                        .addContainerGap())
                    .addGroup(pnl_feriadosLayout.createSequentialGroup()
                        .addComponent(lbl_fecha_feriado)
                        .addGap(18, 18, 18)
                        .addGroup(pnl_feriadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txt_id_feriado)
                            .addComponent(dtc_fecha_feriado1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(dtc_fecha_feriado2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(18, 18, 18)
                        .addComponent(chb_variosDias)
                        .addGap(288, 288, 288))))
        );
        pnl_feriadosLayout.setVerticalGroup(
            pnl_feriadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnl_feriadosLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(txt_id_feriado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(pnl_feriadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnl_feriadosLayout.createSequentialGroup()
                        .addGap(23, 23, 23)
                        .addComponent(chb_variosDias))
                    .addGroup(pnl_feriadosLayout.createSequentialGroup()
                        .addGroup(pnl_feriadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(lbl_fecha_feriado, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(dtc_fecha_feriado1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(dtc_fecha_feriado2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(7, 7, 7)
                .addGroup(pnl_feriadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbl_descripcion_feriado, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(txt_descripcion_feriado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pnl_botones, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane_tabla_feriados, javax.swing.GroupLayout.DEFAULT_SIZE, 271, Short.MAX_VALUE)
                .addContainerGap())
        );

        jtp_contenido.addTab("Días feriados", pnl_feriados);

        getContentPane().add(jtp_contenido, java.awt.BorderLayout.CENTER);

        pnl_pie.setBackground(new java.awt.Color(82, 190, 128));
        pnl_pie.setPreferredSize(new java.awt.Dimension(1280, 40));
        pnl_pie.setLayout(new java.awt.BorderLayout());
        getContentPane().add(pnl_pie, java.awt.BorderLayout.SOUTH);

        setSize(new java.awt.Dimension(656, 679));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btn_guardar_jornadaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_guardar_jornadaActionPerformed
        //Validacion de datos
        if (ych_anho.getValue() != dtc_fecha_inicial.getCalendar().get(Calendar.YEAR)
                || ych_anho.getValue() != dtc_fecha_final.getCalendar().get(Calendar.YEAR)) {
            JOptionPane.showMessageDialog(this, "Los años deben ser los mismos");
            return;
        }

        //Lectura de datos
        Jornada dts = new Jornada();
        dts.setAnho(ych_anho.getValue());
        dts.setFecha_inicial(Auxiliar.SQLDate(dtc_fecha_inicial.getCalendar()));
        dts.setFecha_final(Auxiliar.SQLDate(dtc_fecha_final.getCalendar()));

        //Verificando que la nueva jornada no cause conflictos
        if (new ConsulAgenda().conflictosJornada(dts)) {
            JOptionPane.showMessageDialog(this, "Hay conflictos con alguna(s) agenda(s)\nArreglar antes de guardar");
            return;
        }

        //Envio de datos
        ConsulJornada func = new ConsulJornada();
        if (func.guardar(dts)) {
            JOptionPane.showMessageDialog(this, "Jornada guardada satisfactoriamente");
            MostrarJornadas();
        }

    }//GEN-LAST:event_btn_guardar_jornadaActionPerformed

    private void tab_jornadasMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tab_jornadasMouseClicked
        int fila = tab_jornadas.rowAtPoint(evt.getPoint());
        ych_anho.setValue(Integer.parseInt(tab_jornadas.getValueAt(fila, 0).toString()));
        dtc_fecha_inicial.setDate(Date.valueOf(tab_jornadas.getValueAt(fila, 1).toString()));
        dtc_fecha_final.setDate(Date.valueOf(tab_jornadas.getValueAt(fila, 2).toString()));
    }//GEN-LAST:event_tab_jornadasMouseClicked

    private void btn_fecha_inicial_defaultActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_fecha_inicial_defaultActionPerformed
        dtc_fecha_inicial.setDate(Auxiliar.FirstDayOfTheYear(ych_anho.getValue()));
    }//GEN-LAST:event_btn_fecha_inicial_defaultActionPerformed

    private void btn_fecha_final_defaultActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_fecha_final_defaultActionPerformed
        dtc_fecha_final.setDate(Auxiliar.LastDayOfTheYear(ych_anho.getValue()));
    }//GEN-LAST:event_btn_fecha_final_defaultActionPerformed

    private void tab_feriadosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tab_feriadosMouseClicked
        //Habilitacion de campos
        btn_guardar_feriado.setText("Editar");
        HabilitarFeriado();
        btn_eliminar_feriado.setEnabled(true);
        accionFeriado = "editar";
        chb_variosDias.setEnabled(false);

        //Rellenado de campos
        int fila = tab_feriados.rowAtPoint(evt.getPoint());
        txt_id_feriado.setText(tab_feriados.getValueAt(fila, 0).toString());
        dtc_fecha_feriado1.setDate(Date.valueOf(tab_feriados.getValueAt(fila, 1).toString()));
        txt_descripcion_feriado.setText(tab_feriados.getValueAt(fila, 2).toString());

    }//GEN-LAST:event_tab_feriadosMouseClicked

    private void btn_nuevo_feriadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_nuevo_feriadoActionPerformed
        HabilitarFeriado();
        btn_guardar_feriado.setText("Guardar");
        accionFeriado = "guardar";
        chb_variosDias.setEnabled(true);
    }//GEN-LAST:event_btn_nuevo_feriadoActionPerformed

    private void btn_guardar_feriadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_guardar_feriadoActionPerformed
        //Validacion de datos
        if (txt_descripcion_feriado.getText().equals("")) {
            JOptionPane.showMessageDialog(this, "Se debe ingresar una descripción para el feriado");
            txt_descripcion_feriado.requestFocus();
            return;
        }

        //Lectura de datos
        Feriado dts = new Feriado();
        dts.setDescripcion(txt_descripcion_feriado.getText());

        //Envio de datos
        ConsulFeriado func = new ConsulFeriado();
        if (accionFeriado.equals("guardar")) {
            Calendar cal1 = dtc_fecha_feriado1.getCalendar();
            Calendar cal2;
            //¿El feriado consiste de varios dias seguidos?
            if (chb_variosDias.isSelected()) {
                cal2 = dtc_fecha_feriado2.getCalendar();
            } else {
                cal2 = cal1;
            }
            //Verificando conflictos
            for (Date fecha : Auxiliar.SQLDateRange(cal1, cal2)) {
                //Verificando que no hay conflictos con agendas
                if (new ConsulAgenda().conflictosFeriado(fecha)) {
                    JOptionPane.showMessageDialog(this, "Existen agendas que causan conflictos");
                    return;
                }
                //Verificando que no hay un feriado ya registrado
                if(new ConsulFeriado().verificar(fecha)){
                    JOptionPane.showMessageDialog(this, "Uno de los feriados ya esta registrado");
                    return;
                }
            }
            //Enviando los feriados
            boolean enviados = true;
            for (Date fecha : Auxiliar.SQLDateRange(cal1, cal2)) {
                dts.setFecha(fecha);
                System.out.println("Enviando " + fecha);
                if (!new ConsulFeriado().insertar(dts)) {
                    System.out.println("No se envio");
                    enviados = false;
                    break;
                }
            }
            //Mostrando mensaje de feriado(s) registrado(s)
            if (enviados) {
                JOptionPane.showMessageDialog(this, "Feriado(s) registrado(s) satisfactoriamente");
                MostrarFeriados();
                InhabilitarFeriado();
            }
        } else if (accionFeriado.equals("editar")) {
            dts.setId(Integer.parseInt(txt_id_feriado.getText()));
            if (func.editar(dts)) {
                JOptionPane.showMessageDialog(this, "Feriado editado satisfactoriamente");
                MostrarFeriados();
                InhabilitarFeriado();
            }
        }
    }//GEN-LAST:event_btn_guardar_feriadoActionPerformed

    private void btn_eliminar_feriadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_eliminar_feriadoActionPerformed
        if (!txt_id_feriado.getText().equals("")) {
            int confirmacion = JOptionPane.showConfirmDialog(this, "¿Estás seguro de eliminar el feriado?", "Confirmar", 2);
            if (confirmacion == 0) {
                //Lectura y obtencion de datos
                Feriado dts = new ConsulFeriado().obtener(Integer.parseInt(txt_id_feriado.getText()));
                //Envio de datos
                ConsulFeriado func = new ConsulFeriado();
                //Verificando conflictos
                if (new ConsulAgenda().conflictosFeriado(dts.getFecha())) {
                    JOptionPane.showMessageDialog(this, "Existen agendas que causan conflictos");
                    return;
                }
                if (func.eliminar(dts)) {
                    JOptionPane.showMessageDialog(this, "Feriado eliminado satisfactoriamente");
                    MostrarFeriados();
                    InhabilitarFeriado();
                }
            }
        }
    }//GEN-LAST:event_btn_eliminar_feriadoActionPerformed

    private void chb_variosDiasStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_chb_variosDiasStateChanged
        if (chb_variosDias.isSelected()) {
            dtc_fecha_feriado2.setEnabled(true);
            dtc_fecha_feriado2.setCalendar(dtc_fecha_feriado1.getCalendar());
        } else {
            dtc_fecha_feriado2.setEnabled(false);
        }
    }//GEN-LAST:event_chb_variosDiasStateChanged

    private void btn_guardar_dias_laboralesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_guardar_dias_laboralesActionPerformed
        //Lectura de datos
        boolean[] dts = new boolean[7];
        dts[0] = chb_domingo.isSelected();
        dts[1] = chb_lunes.isSelected();
        dts[2] = chb_martes.isSelected();
        dts[3] = chb_miercoles.isSelected();
        dts[4] = chb_jueves.isSelected();
        dts[5] = chb_viernes.isSelected();
        dts[6] = chb_sabado.isSelected();
        
        //Verificando si hay agendas registradas
        if (new ConsulAgenda().conflictosDiasLaborales()) {
            String msg = "Se han registrado agendas hata ahora\n"
                    + "Para cambiar los dias laborales elimine todas las agendas primero\n"
                    + "Recuerde que puede exportar la informacion de las agendas a PDF o Excel antes de eliminarlas";
            JOptionPane.showMessageDialog(this, msg);
            return;
        }

        //Envio de datos
        ConsulDiasLaborales func = new ConsulDiasLaborales();
        if (func.actualizar(dts)) {
            JOptionPane.showMessageDialog(this, "Días laborales actualizados satisfactoriamente");
        }
    }//GEN-LAST:event_btn_guardar_dias_laboralesActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frm_dias.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frm_dias.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frm_dias.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frm_dias.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frm_dias().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_eliminar_feriado;
    private javax.swing.JButton btn_fecha_final_default;
    private javax.swing.JButton btn_fecha_inicial_default;
    private javax.swing.JButton btn_guardar_dias_laborales;
    private javax.swing.JButton btn_guardar_feriado;
    private javax.swing.JButton btn_guardar_jornada;
    private javax.swing.JButton btn_nuevo_feriado;
    private javax.swing.JCheckBox chb_domingo;
    private javax.swing.JCheckBox chb_jueves;
    private javax.swing.JCheckBox chb_lunes;
    private javax.swing.JCheckBox chb_martes;
    private javax.swing.JCheckBox chb_miercoles;
    private javax.swing.JCheckBox chb_sabado;
    private javax.swing.JCheckBox chb_variosDias;
    private javax.swing.JCheckBox chb_viernes;
    private com.toedter.calendar.JDateChooser dtc_fecha_feriado1;
    private com.toedter.calendar.JDateChooser dtc_fecha_feriado2;
    private com.toedter.calendar.JDateChooser dtc_fecha_final;
    private com.toedter.calendar.JDateChooser dtc_fecha_inicial;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane_tabla_feriados;
    private javax.swing.JScrollPane jScrollPane_tabla_jornadas;
    private javax.swing.JTabbedPane jtp_contenido;
    private javax.swing.JLabel lbl_anho;
    private javax.swing.JLabel lbl_descripcion_feriado;
    private javax.swing.JLabel lbl_fecha_feriado;
    private javax.swing.JLabel lbl_fecha_final;
    private javax.swing.JLabel lbl_fecha_inicial;
    private javax.swing.JLabel lbl_titulo;
    private javax.swing.JPanel pnl_botones;
    private javax.swing.JPanel pnl_cabecera;
    private javax.swing.JPanel pnl_dias;
    private javax.swing.JPanel pnl_dias_laborales;
    private javax.swing.JPanel pnl_feriados;
    private javax.swing.JPanel pnl_jornada_anual;
    private javax.swing.JPanel pnl_pie;
    private javax.swing.JPanel pnl_sesion_info;
    private javax.swing.JTable tab_feriados;
    private javax.swing.JTable tab_jornadas;
    private javax.swing.JTextField txt_descripcion_feriado;
    private javax.swing.JTextField txt_id_feriado;
    private com.toedter.calendar.JYearChooser ych_anho;
    // End of variables declaration//GEN-END:variables
}
