package ventanas;

import consultas.ConsulArea;
import consultas.ConsulMaquina;
import consultas.ConsulMaquinaria;

public class frm_buscar_maquina extends javax.swing.JFrame {

    public static String destino = "";
    
    public frm_buscar_maquina() {
        initComponents();
        
        //Rellena los combobox
        ListaAreas();
        ListaMaquinarias();
        
        //Muestra las maquinas
        MostrarMaquinas();
    }

    //Escribe las areas registradas en el combobox
    public static void ListaAreas() {
        cmb_areas.setModel(new ConsulArea().lista());
    }

    //Escribe las maquinarias registradas en el combobox
    public static void ListaMaquinarias() {
        cmb_maquinarias.setModel(new ConsulMaquinaria().lista(cmb_areas.getSelectedItem().toString()));
    }

    //Muestra las maquina segun el area y la maquinaria
    private void MostrarMaquinas() {
        String area = cmb_areas.getSelectedItem().toString();
        String maquinaria = cmb_maquinarias.getSelectedItem().toString();
        tab_maquinas.setModel(new ConsulMaquina().mostrar(area, maquinaria));
        OcultarColumnasMaquina();
        lbl_num_registros_maquina.setText("Número de máquinas: " + ConsulMaquina.num_registros);
    }

    private void OcultarColumnasMaquina() {
        int[] columnas = {0, 3};
        for (int columna : columnas) {
            tab_maquinas.getColumnModel().getColumn(columna).setMaxWidth(0);
            tab_maquinas.getColumnModel().getColumn(columna).setMinWidth(0);
            tab_maquinas.getColumnModel().getColumn(columna).setPreferredWidth(0);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnl_maquinas = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        tab_maquinas = new javax.swing.JTable();
        lbl_num_registros_maquina = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        cmb_areas = new javax.swing.JComboBox<>();
        jLabel9 = new javax.swing.JLabel();
        cmb_maquinarias = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Maquinas");
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setSize(new java.awt.Dimension(640, 640));

        pnl_maquinas.setBackground(new java.awt.Color(255, 255, 255));

        tab_maquinas.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tab_maquinas.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                tab_maquinasMousePressed(evt);
            }
        });
        jScrollPane3.setViewportView(tab_maquinas);

        lbl_num_registros_maquina.setText("Número de máquinas:");

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel1.setText("Areas de trabajo:");

        cmb_areas.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cmb_areasItemStateChanged(evt);
            }
        });

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel9.setText("Máquinaria:");

        cmb_maquinarias.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cmb_maquinariasItemStateChanged(evt);
            }
        });

        javax.swing.GroupLayout pnl_maquinasLayout = new javax.swing.GroupLayout(pnl_maquinas);
        pnl_maquinas.setLayout(pnl_maquinasLayout);
        pnl_maquinasLayout.setHorizontalGroup(
            pnl_maquinasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnl_maquinasLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnl_maquinasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 620, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnl_maquinasLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(lbl_num_registros_maquina))
                    .addGroup(pnl_maquinasLayout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(18, 18, 18)
                        .addComponent(cmb_areas, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel9)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cmb_maquinarias, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap())
        );
        pnl_maquinasLayout.setVerticalGroup(
            pnl_maquinasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnl_maquinasLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnl_maquinasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(cmb_areas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel9)
                    .addComponent(cmb_maquinarias, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 572, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lbl_num_registros_maquina)
                .addContainerGap())
        );

        getContentPane().add(pnl_maquinas, java.awt.BorderLayout.CENTER);

        setSize(new java.awt.Dimension(656, 679));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void cmb_areasItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cmb_areasItemStateChanged
        ListaMaquinarias();
        MostrarMaquinas();
    }//GEN-LAST:event_cmb_areasItemStateChanged

    private void cmb_maquinariasItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cmb_maquinariasItemStateChanged
        MostrarMaquinas();
    }//GEN-LAST:event_cmb_maquinariasItemStateChanged

    private void tab_maquinasMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tab_maquinasMousePressed
        if (evt.getClickCount() == 2) {
            
            int fila = tab_maquinas.getSelectedRow();
            if (destino.equals("AG")) {
                frm_agenda.txt_id_maquina.setText(tab_maquinas.getValueAt(fila, 0).toString());
                frm_agenda.txt_codigo_maquina.setText(tab_maquinas.getValueAt(fila, 1).toString());
                frm_agenda.txt_id_mantenimiento.setText("");
                frm_agenda.txt_nombre_mantenimiento.setText("");
            }else if (destino.equals("EJ")) {
                frm_ejecucion.txt_id_maquina.setText(tab_maquinas.getValueAt(fila, 0).toString());
                frm_ejecucion.txt_codigo_maquina.setText(tab_maquinas.getValueAt(fila, 1).toString());
                frm_ejecucion.txt_id_mantenimiento.setText("");
                frm_ejecucion.txt_codigo_mantenimiento.setText("");
                frm_ejecucion.txt_nombre_mantenimiento.setText("");
                frm_ejecucion.txt_tipo_mantenimiento.setText("");
            }
            
            this.dispose();
        }
    }//GEN-LAST:event_tab_maquinasMousePressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frm_buscar_maquina.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frm_buscar_maquina.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frm_buscar_maquina.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frm_buscar_maquina.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frm_buscar_maquina().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public static javax.swing.JComboBox<String> cmb_areas;
    public static javax.swing.JComboBox<String> cmb_maquinarias;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane3;
    private static javax.swing.JLabel lbl_num_registros_maquina;
    private javax.swing.JPanel pnl_maquinas;
    private javax.swing.JTable tab_maquinas;
    // End of variables declaration//GEN-END:variables
}
