package ventanas;

import consultas.ConsulArea;
import consultas.ConsulMaquinaria;

public class frm_buscar_maquinarias extends javax.swing.JFrame {
    
    public static String destino = "";
    
    public frm_buscar_maquinarias() {
        initComponents();
        
        //Rellena las areas y muestra las maquinarias
        ListaAreas();
        MostrarMaquinarias();
    }
    
    //Escribe las areas registradas en el combobox
    public static void ListaAreas() {
        cmb_areas.setModel(new ConsulArea().lista());
    }

    //Muestra las maquinarias segun el area
    public static void MostrarMaquinarias() {
        tab_maquinarias.setModel(new ConsulMaquinaria().mostrar(cmb_areas.getSelectedItem().toString()));
        OcultarColumnasMaquinaria();
        lbl_num_registros_maquinaria.setText("Número de maquinarias: " + ConsulMaquinaria.num_registros);
    }

    private static void OcultarColumnasMaquinaria() {
        int[] columnas = {0, 1};
        for (int columna : columnas) {
            tab_maquinarias.getColumnModel().getColumn(columna).setMaxWidth(0);
            tab_maquinarias.getColumnModel().getColumn(columna).setMinWidth(0);
            tab_maquinarias.getColumnModel().getColumn(columna).setPreferredWidth(0);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnl_tabla1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        cmb_areas = new javax.swing.JComboBox<>();
        jScrollPane1 = new javax.swing.JScrollPane();
        tab_maquinarias = new javax.swing.JTable();
        lbl_num_registros_maquinaria = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Seleccionar maquinaria");
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setSize(new java.awt.Dimension(640, 640));

        pnl_tabla1.setBackground(new java.awt.Color(255, 255, 255));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel1.setText("Areas de trabajo:");

        cmb_areas.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cmb_areasItemStateChanged(evt);
            }
        });

        tab_maquinarias.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tab_maquinarias.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                tab_maquinariasMousePressed(evt);
            }
        });
        jScrollPane1.setViewportView(tab_maquinarias);

        lbl_num_registros_maquinaria.setText("Número de maquinarias:");

        javax.swing.GroupLayout pnl_tabla1Layout = new javax.swing.GroupLayout(pnl_tabla1);
        pnl_tabla1.setLayout(pnl_tabla1Layout);
        pnl_tabla1Layout.setHorizontalGroup(
            pnl_tabla1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnl_tabla1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnl_tabla1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 620, Short.MAX_VALUE)
                    .addGroup(pnl_tabla1Layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(18, 18, 18)
                        .addComponent(cmb_areas, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnl_tabla1Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(lbl_num_registros_maquinaria)))
                .addContainerGap())
        );
        pnl_tabla1Layout.setVerticalGroup(
            pnl_tabla1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnl_tabla1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnl_tabla1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(cmb_areas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(6, 6, 6)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 572, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lbl_num_registros_maquinaria)
                .addContainerGap())
        );

        getContentPane().add(pnl_tabla1, java.awt.BorderLayout.CENTER);

        setSize(new java.awt.Dimension(656, 679));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void cmb_areasItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cmb_areasItemStateChanged
        MostrarMaquinarias();
    }//GEN-LAST:event_cmb_areasItemStateChanged

    private void tab_maquinariasMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tab_maquinariasMousePressed
        if (evt.getClickCount() == 2) {
            
            int fila = tab_maquinarias.getSelectedRow();
            if (destino.equals("MP")) {//Si lo llama la ventana de mantenimientos preventivos
                frm_mant_prev.txt_id_maquinaria.setText(tab_maquinarias.getValueAt(fila, 0).toString());
                frm_mant_prev.txt_codigo_maquinaria.setText(tab_maquinarias.getValueAt(fila, 3).toString());
            } else if (destino.equals("MC")) {//Si lo llama la ventana de mantenimientos correctivos
                frm_mant_corr.txt_id_maquinaria.setText(tab_maquinarias.getValueAt(fila, 0).toString());
                frm_mant_corr.txt_codigo_maquinaria.setText(tab_maquinarias.getValueAt(fila, 3).toString());
            }
            
            this.dispose();
        }
    }//GEN-LAST:event_tab_maquinariasMousePressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frm_buscar_maquinarias.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frm_buscar_maquinarias.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frm_buscar_maquinarias.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frm_buscar_maquinarias.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frm_buscar_maquinarias().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public static javax.swing.JComboBox<String> cmb_areas;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private static javax.swing.JLabel lbl_num_registros_maquinaria;
    private javax.swing.JPanel pnl_tabla1;
    private static javax.swing.JTable tab_maquinarias;
    // End of variables declaration//GEN-END:variables
}
