package ventanas;

import clases.Maquina;
import clases.Maquinaria;
import consultas.ConsulAgenda;
import consultas.ConsulArea;
import consultas.ConsulMantenimiento;
import consultas.ConsulMaquina;
import consultas.ConsulMaquinaria;
import javax.swing.JOptionPane;
import paneles.*;

public class frm_maquinas extends javax.swing.JFrame {

    public static String ventana = "";

    private String accionMaquinaria = "guardar";
    private String accionMaquina = "guardar";

    public frm_maquinas() {
        initComponents();
        
        //Paneles
        pnl_sesion_info.add(new pnl_sesionde());
        pnl_pie.add(new pnl_footer());

        //Panel maquinarias
        ListaAreas();
        MostrarMaquinarias();
        
        //Panel maquinas
        ListaMaquinarias();
        MostrarMaquinas();
    }

    //Escribe las areas registradas en el combobox
    public static void ListaAreas() {
        cmb_areas.setModel(new ConsulArea().lista());
    }

    //Escribe las maquinarias registradas en el combobox
    private void ListaMaquinarias() {
        cmb_maquinarias.setModel(new ConsulMaquinaria().lista(cmb_areas.getSelectedItem().toString()));
    }

    private void InhabilitarMaquinaria() {
        txt_codigo_maquinaria.setEnabled(false);
        txt_descripcion_maquinaria.setEnabled(false);

        txt_id_maquinaria.setText("");
        txt_codigo_maquinaria.setText("");
        txt_id_area.setText("");
        txt_nombre_area.setText("");
        txt_descripcion_maquinaria.setText("");

        btn_buscar_area.setEnabled(false);
        btn_guardar_maquinaria.setEnabled(false);
        btn_eliminar_maquinaria.setEnabled(false);
    }

    private void HabilitarMaquinaria() {
        txt_codigo_maquinaria.setEnabled(true);
        txt_descripcion_maquinaria.setEnabled(true);

        txt_id_maquinaria.setText("");
        txt_codigo_maquinaria.setText("");
        txt_id_area.setText("");
        txt_nombre_area.setText("");
        txt_descripcion_maquinaria.setText("");

        btn_buscar_area.setEnabled(true);
        btn_guardar_maquinaria.setEnabled(true);
        btn_eliminar_maquinaria.setEnabled(false);
    }

    //Muestra las maquinarias segun el area
    public static void MostrarMaquinarias() {
        tab_maquinarias.setModel(new ConsulMaquinaria().mostrar(cmb_areas.getSelectedItem().toString()));
        OcultarColumnasMaquinaria();
        lbl_num_registros_maquinaria.setText("Número de maquinarias: " + ConsulMaquinaria.num_registros);
    }

    private static void OcultarColumnasMaquinaria() {
        int[] columnas = {0, 1};
        for (int columna : columnas) {
            tab_maquinarias.getColumnModel().getColumn(columna).setMaxWidth(0);
            tab_maquinarias.getColumnModel().getColumn(columna).setMinWidth(0);
            tab_maquinarias.getColumnModel().getColumn(columna).setPreferredWidth(0);
        }
    }

    private void InhabilitarMaquina() {
        txt_codigo_maquina.setEnabled(false);
        txt_nombre_maquina.setEnabled(false);

        txt_id_maquina.setText("");
        txt_id_maquinaria2.setText("");
        txt_codigo_maquinaria2.setText("");
        txt_codigo_maquina.setText("");
        txt_nombre_maquina.setText("");

        btn_guardar_maquina.setEnabled(false);
        btn_eliminar_maquina.setEnabled(false);
    }

    private void HabilitarMaquina() {
        txt_codigo_maquina.setEnabled(true);
        txt_nombre_maquina.setEnabled(true);

        txt_id_maquina.setText("");
        txt_id_maquinaria2.setText("");
        txt_codigo_maquinaria2.setText("");
        txt_codigo_maquina.setText("");
        txt_nombre_maquina.setText("");

        btn_guardar_maquina.setEnabled(true);
        btn_eliminar_maquina.setEnabled(false);
    }

    //Muestra las maquinarias segun el area
    private void MostrarMaquinas() {
        String area = cmb_areas.getSelectedItem().toString();
        String maquinaria = cmb_maquinarias.getSelectedItem().toString();
        tab_maquinas.setModel(new ConsulMaquina().mostrar(area, maquinaria));
        OcultarColumnasMaquina();
        lbl_num_registros_maquina.setText("Número de maquinarias: " + ConsulMaquina.num_registros);
    }

    private void OcultarColumnasMaquina() {
        int[] columnas = {0, 3};
        for (int columna : columnas) {
            tab_maquinas.getColumnModel().getColumn(columna).setMaxWidth(0);
            tab_maquinas.getColumnModel().getColumn(columna).setMinWidth(0);
            tab_maquinas.getColumnModel().getColumn(columna).setPreferredWidth(0);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnl_cabecera = new javax.swing.JPanel();
        lbl_titulo = new javax.swing.JLabel();
        pnl_sesion_info = new javax.swing.JPanel();
        pnl_contenido = new javax.swing.JPanel();
        pnl_controles_maquinaria = new javax.swing.JPanel();
        txt_id_maquinaria = new javax.swing.JTextField();
        lbl_area = new javax.swing.JLabel();
        txt_id_area = new javax.swing.JTextField();
        txt_nombre_area = new javax.swing.JTextField();
        btn_buscar_area = new javax.swing.JButton();
        lbl_codigo_maquinaria = new javax.swing.JLabel();
        txt_codigo_maquinaria = new javax.swing.JTextField();
        lbl_descripcion_maquinaria = new javax.swing.JLabel();
        jScrollPane_descripcion_maquinaria = new javax.swing.JScrollPane();
        txt_descripcion_maquinaria = new javax.swing.JTextArea();
        pnl_botones_maquinaria = new javax.swing.JPanel();
        btn_nuevo_maquinaria = new javax.swing.JButton();
        btn_guardar_maquinaria = new javax.swing.JButton();
        btn_eliminar_maquinaria = new javax.swing.JButton();
        pnl_tabla_maquinaria = new javax.swing.JPanel();
        lbl_buscar_area = new javax.swing.JLabel();
        cmb_areas = new javax.swing.JComboBox<>();
        btn_gestionar_areas = new javax.swing.JButton();
        jScrollPane_tabla_maquinaria = new javax.swing.JScrollPane();
        tab_maquinarias = new javax.swing.JTable();
        lbl_num_registros_maquinaria = new javax.swing.JLabel();
        pnl_controles_maquina = new javax.swing.JPanel();
        txt_id_maquina = new javax.swing.JTextField();
        lbl_maquinaria = new javax.swing.JLabel();
        txt_id_maquinaria2 = new javax.swing.JTextField();
        txt_codigo_maquinaria2 = new javax.swing.JTextField();
        lbl_codigo_maquina = new javax.swing.JLabel();
        txt_codigo_maquina = new javax.swing.JTextField();
        lbl_nombre_maquina = new javax.swing.JLabel();
        txt_nombre_maquina = new javax.swing.JTextField();
        pnl_botones_maquina = new javax.swing.JPanel();
        btn_nuevo_maquina = new javax.swing.JButton();
        btn_guardar_maquina = new javax.swing.JButton();
        btn_eliminar_maquina = new javax.swing.JButton();
        pnl_tabla_maquina = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        cmb_maquinarias = new javax.swing.JComboBox<>();
        jScrollPane_tabla_maquina = new javax.swing.JScrollPane();
        tab_maquinas = new javax.swing.JTable();
        lbl_num_registros_maquina = new javax.swing.JLabel();
        pnl_pie = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Maquinas");
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setSize(new java.awt.Dimension(1280, 640));
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosed(java.awt.event.WindowEvent evt) {
                formWindowClosed(evt);
            }
        });
        getContentPane().setLayout(new java.awt.BorderLayout(0, 4));

        pnl_cabecera.setBackground(new java.awt.Color(34, 112, 147));
        pnl_cabecera.setPreferredSize(new java.awt.Dimension(1280, 80));
        pnl_cabecera.setLayout(new java.awt.BorderLayout());

        lbl_titulo.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        lbl_titulo.setForeground(new java.awt.Color(255, 255, 255));
        lbl_titulo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl_titulo.setText("GESTOR DE MAQUINAS");
        pnl_cabecera.add(lbl_titulo, java.awt.BorderLayout.CENTER);

        pnl_sesion_info.setBackground(new java.awt.Color(52, 172, 224));
        pnl_sesion_info.setPreferredSize(new java.awt.Dimension(120, 80));
        pnl_sesion_info.setLayout(new java.awt.GridLayout(1, 0));
        pnl_cabecera.add(pnl_sesion_info, java.awt.BorderLayout.LINE_END);

        getContentPane().add(pnl_cabecera, java.awt.BorderLayout.PAGE_START);

        pnl_contenido.setBackground(new java.awt.Color(204, 204, 204));
        pnl_contenido.setLayout(new java.awt.GridLayout(2, 0, 4, 4));

        pnl_controles_maquinaria.setBackground(new java.awt.Color(255, 255, 255));

        txt_id_maquinaria.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txt_id_maquinaria.setEnabled(false);

        lbl_area.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lbl_area.setText("Area:");

        txt_id_area.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txt_id_area.setEnabled(false);

        txt_nombre_area.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txt_nombre_area.setEnabled(false);

        btn_buscar_area.setText("...");
        btn_buscar_area.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_buscar_areaActionPerformed(evt);
            }
        });

        lbl_codigo_maquinaria.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lbl_codigo_maquinaria.setText("Código:");

        txt_codigo_maquinaria.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txt_codigo_maquinaria.setEnabled(false);

        lbl_descripcion_maquinaria.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lbl_descripcion_maquinaria.setText("Descripción:");

        txt_descripcion_maquinaria.setColumns(20);
        txt_descripcion_maquinaria.setLineWrap(true);
        txt_descripcion_maquinaria.setRows(4);
        txt_descripcion_maquinaria.setEnabled(false);
        jScrollPane_descripcion_maquinaria.setViewportView(txt_descripcion_maquinaria);

        pnl_botones_maquinaria.setLayout(new java.awt.GridLayout(1, 0, 4, 4));

        btn_nuevo_maquinaria.setBackground(new java.awt.Color(204, 204, 204));
        btn_nuevo_maquinaria.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btn_nuevo_maquinaria.setText("Nuevo");
        btn_nuevo_maquinaria.setContentAreaFilled(false);
        btn_nuevo_maquinaria.setOpaque(true);
        btn_nuevo_maquinaria.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_nuevo_maquinariaActionPerformed(evt);
            }
        });
        pnl_botones_maquinaria.add(btn_nuevo_maquinaria);

        btn_guardar_maquinaria.setBackground(new java.awt.Color(204, 204, 204));
        btn_guardar_maquinaria.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btn_guardar_maquinaria.setText("Guardar");
        btn_guardar_maquinaria.setContentAreaFilled(false);
        btn_guardar_maquinaria.setEnabled(false);
        btn_guardar_maquinaria.setOpaque(true);
        btn_guardar_maquinaria.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_guardar_maquinariaActionPerformed(evt);
            }
        });
        pnl_botones_maquinaria.add(btn_guardar_maquinaria);

        btn_eliminar_maquinaria.setBackground(new java.awt.Color(204, 204, 204));
        btn_eliminar_maquinaria.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btn_eliminar_maquinaria.setText("Eliminar");
        btn_eliminar_maquinaria.setContentAreaFilled(false);
        btn_eliminar_maquinaria.setEnabled(false);
        btn_eliminar_maquinaria.setOpaque(true);
        btn_eliminar_maquinaria.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_eliminar_maquinariaActionPerformed(evt);
            }
        });
        pnl_botones_maquinaria.add(btn_eliminar_maquinaria);

        javax.swing.GroupLayout pnl_controles_maquinariaLayout = new javax.swing.GroupLayout(pnl_controles_maquinaria);
        pnl_controles_maquinaria.setLayout(pnl_controles_maquinariaLayout);
        pnl_controles_maquinariaLayout.setHorizontalGroup(
            pnl_controles_maquinariaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnl_controles_maquinariaLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnl_controles_maquinariaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(pnl_botones_maquinaria, javax.swing.GroupLayout.DEFAULT_SIZE, 618, Short.MAX_VALUE)
                    .addGroup(pnl_controles_maquinariaLayout.createSequentialGroup()
                        .addGroup(pnl_controles_maquinariaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(pnl_controles_maquinariaLayout.createSequentialGroup()
                                .addGroup(pnl_controles_maquinariaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lbl_codigo_maquinaria)
                                    .addComponent(lbl_area))
                                .addGap(47, 47, 47))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnl_controles_maquinariaLayout.createSequentialGroup()
                                .addComponent(lbl_descripcion_maquinaria)
                                .addGap(18, 18, 18)))
                        .addGroup(pnl_controles_maquinariaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txt_codigo_maquinaria)
                            .addComponent(jScrollPane_descripcion_maquinaria)
                            .addGroup(pnl_controles_maquinariaLayout.createSequentialGroup()
                                .addComponent(txt_id_maquinaria, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(pnl_controles_maquinariaLayout.createSequentialGroup()
                                .addComponent(txt_id_area, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txt_nombre_area)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btn_buscar_area)))))
                .addContainerGap())
        );
        pnl_controles_maquinariaLayout.setVerticalGroup(
            pnl_controles_maquinariaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnl_controles_maquinariaLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(txt_id_maquinaria, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnl_controles_maquinariaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txt_id_area, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt_nombre_area, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_buscar_area)
                    .addComponent(lbl_area))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnl_controles_maquinariaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbl_codigo_maquinaria)
                    .addComponent(txt_codigo_maquinaria, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnl_controles_maquinariaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnl_controles_maquinariaLayout.createSequentialGroup()
                        .addComponent(jScrollPane_descripcion_maquinaria, javax.swing.GroupLayout.DEFAULT_SIZE, 80, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(pnl_botones_maquinaria, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(pnl_controles_maquinariaLayout.createSequentialGroup()
                        .addComponent(lbl_descripcion_maquinaria)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );

        pnl_contenido.add(pnl_controles_maquinaria);

        pnl_tabla_maquinaria.setBackground(new java.awt.Color(255, 255, 255));

        lbl_buscar_area.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lbl_buscar_area.setText("Areas de trabajo:");

        cmb_areas.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cmb_areasItemStateChanged(evt);
            }
        });

        btn_gestionar_areas.setText("Gestionar Areas");
        btn_gestionar_areas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_gestionar_areasActionPerformed(evt);
            }
        });

        tab_maquinarias.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tab_maquinarias.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tab_maquinariasMouseClicked(evt);
            }
        });
        jScrollPane_tabla_maquinaria.setViewportView(tab_maquinarias);

        lbl_num_registros_maquinaria.setText("Número de maquinarias:");

        javax.swing.GroupLayout pnl_tabla_maquinariaLayout = new javax.swing.GroupLayout(pnl_tabla_maquinaria);
        pnl_tabla_maquinaria.setLayout(pnl_tabla_maquinariaLayout);
        pnl_tabla_maquinariaLayout.setHorizontalGroup(
            pnl_tabla_maquinariaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnl_tabla_maquinariaLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnl_tabla_maquinariaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane_tabla_maquinaria, javax.swing.GroupLayout.DEFAULT_SIZE, 618, Short.MAX_VALUE)
                    .addGroup(pnl_tabla_maquinariaLayout.createSequentialGroup()
                        .addComponent(lbl_buscar_area)
                        .addGap(18, 18, 18)
                        .addComponent(cmb_areas, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btn_gestionar_areas, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnl_tabla_maquinariaLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(lbl_num_registros_maquinaria)))
                .addContainerGap())
        );
        pnl_tabla_maquinariaLayout.setVerticalGroup(
            pnl_tabla_maquinariaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnl_tabla_maquinariaLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnl_tabla_maquinariaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbl_buscar_area)
                    .addComponent(cmb_areas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_gestionar_areas))
                .addGap(4, 4, 4)
                .addComponent(jScrollPane_tabla_maquinaria, javax.swing.GroupLayout.DEFAULT_SIZE, 185, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lbl_num_registros_maquinaria)
                .addContainerGap())
        );

        pnl_contenido.add(pnl_tabla_maquinaria);

        pnl_controles_maquina.setBackground(new java.awt.Color(255, 255, 255));

        txt_id_maquina.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txt_id_maquina.setEnabled(false);

        lbl_maquinaria.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lbl_maquinaria.setText("Maquinaria:");

        txt_id_maquinaria2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txt_id_maquinaria2.setEnabled(false);

        txt_codigo_maquinaria2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txt_codigo_maquinaria2.setEnabled(false);

        lbl_codigo_maquina.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lbl_codigo_maquina.setText("Código:");

        txt_codigo_maquina.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txt_codigo_maquina.setEnabled(false);

        lbl_nombre_maquina.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lbl_nombre_maquina.setText("Nombre:");

        txt_nombre_maquina.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txt_nombre_maquina.setEnabled(false);

        pnl_botones_maquina.setLayout(new java.awt.GridLayout(1, 0, 4, 4));

        btn_nuevo_maquina.setBackground(new java.awt.Color(204, 204, 204));
        btn_nuevo_maquina.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btn_nuevo_maquina.setText("Nuevo");
        btn_nuevo_maquina.setContentAreaFilled(false);
        btn_nuevo_maquina.setOpaque(true);
        btn_nuevo_maquina.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_nuevo_maquinaActionPerformed(evt);
            }
        });
        pnl_botones_maquina.add(btn_nuevo_maquina);

        btn_guardar_maquina.setBackground(new java.awt.Color(204, 204, 204));
        btn_guardar_maquina.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btn_guardar_maquina.setText("Guardar");
        btn_guardar_maquina.setContentAreaFilled(false);
        btn_guardar_maquina.setEnabled(false);
        btn_guardar_maquina.setOpaque(true);
        btn_guardar_maquina.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_guardar_maquinaActionPerformed(evt);
            }
        });
        pnl_botones_maquina.add(btn_guardar_maquina);

        btn_eliminar_maquina.setBackground(new java.awt.Color(204, 204, 204));
        btn_eliminar_maquina.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btn_eliminar_maquina.setText("Eliminar");
        btn_eliminar_maquina.setContentAreaFilled(false);
        btn_eliminar_maquina.setEnabled(false);
        btn_eliminar_maquina.setOpaque(true);
        btn_eliminar_maquina.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_eliminar_maquinaActionPerformed(evt);
            }
        });
        pnl_botones_maquina.add(btn_eliminar_maquina);

        javax.swing.GroupLayout pnl_controles_maquinaLayout = new javax.swing.GroupLayout(pnl_controles_maquina);
        pnl_controles_maquina.setLayout(pnl_controles_maquinaLayout);
        pnl_controles_maquinaLayout.setHorizontalGroup(
            pnl_controles_maquinaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnl_controles_maquinaLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnl_controles_maquinaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(pnl_botones_maquina, javax.swing.GroupLayout.DEFAULT_SIZE, 618, Short.MAX_VALUE)
                    .addGroup(pnl_controles_maquinaLayout.createSequentialGroup()
                        .addGroup(pnl_controles_maquinaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lbl_nombre_maquina)
                            .addComponent(lbl_codigo_maquina)
                            .addComponent(lbl_maquinaria))
                        .addGap(18, 18, 18)
                        .addGroup(pnl_controles_maquinaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txt_codigo_maquina)
                            .addComponent(txt_nombre_maquina)
                            .addGroup(pnl_controles_maquinaLayout.createSequentialGroup()
                                .addComponent(txt_id_maquina, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(pnl_controles_maquinaLayout.createSequentialGroup()
                                .addComponent(txt_id_maquinaria2, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txt_codigo_maquinaria2)))))
                .addContainerGap())
        );
        pnl_controles_maquinaLayout.setVerticalGroup(
            pnl_controles_maquinaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnl_controles_maquinaLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(txt_id_maquina, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnl_controles_maquinaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnl_controles_maquinaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(txt_id_maquinaria2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(txt_codigo_maquinaria2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(lbl_maquinaria))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnl_controles_maquinaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbl_codigo_maquina)
                    .addComponent(txt_codigo_maquina, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnl_controles_maquinaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lbl_nombre_maquina)
                    .addComponent(txt_nombre_maquina, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 65, Short.MAX_VALUE)
                .addComponent(pnl_botones_maquina, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pnl_contenido.add(pnl_controles_maquina);

        pnl_tabla_maquina.setBackground(new java.awt.Color(255, 255, 255));

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel5.setText("Maquinaria:");

        cmb_maquinarias.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cmb_maquinariasItemStateChanged(evt);
            }
        });

        tab_maquinas.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tab_maquinas.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tab_maquinasMouseClicked(evt);
            }
        });
        jScrollPane_tabla_maquina.setViewportView(tab_maquinas);

        lbl_num_registros_maquina.setText("Número de máquinas:");

        javax.swing.GroupLayout pnl_tabla_maquinaLayout = new javax.swing.GroupLayout(pnl_tabla_maquina);
        pnl_tabla_maquina.setLayout(pnl_tabla_maquinaLayout);
        pnl_tabla_maquinaLayout.setHorizontalGroup(
            pnl_tabla_maquinaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnl_tabla_maquinaLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnl_tabla_maquinaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane_tabla_maquina, javax.swing.GroupLayout.DEFAULT_SIZE, 618, Short.MAX_VALUE)
                    .addGroup(pnl_tabla_maquinaLayout.createSequentialGroup()
                        .addComponent(jLabel5)
                        .addGap(18, 18, 18)
                        .addComponent(cmb_maquinarias, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnl_tabla_maquinaLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(lbl_num_registros_maquina)))
                .addContainerGap())
        );
        pnl_tabla_maquinaLayout.setVerticalGroup(
            pnl_tabla_maquinaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnl_tabla_maquinaLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnl_tabla_maquinaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(cmb_maquinarias, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane_tabla_maquina, javax.swing.GroupLayout.DEFAULT_SIZE, 186, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lbl_num_registros_maquina)
                .addContainerGap())
        );

        pnl_contenido.add(pnl_tabla_maquina);

        getContentPane().add(pnl_contenido, java.awt.BorderLayout.CENTER);

        pnl_pie.setBackground(new java.awt.Color(82, 190, 128));
        pnl_pie.setPreferredSize(new java.awt.Dimension(1280, 40));
        pnl_pie.setLayout(new java.awt.BorderLayout());
        getContentPane().add(pnl_pie, java.awt.BorderLayout.SOUTH);

        setSize(new java.awt.Dimension(1296, 679));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btn_guardar_maquinariaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_guardar_maquinariaActionPerformed
        //Validacion de datos
        if (txt_id_area.getText().equals("")) {
            JOptionPane.showMessageDialog(this, "Se debe seleccionar el area para la maquinaria");
            btn_buscar_area.requestFocus();
            return;
        }
        if (txt_codigo_maquinaria.getText().equals("")) {
            JOptionPane.showMessageDialog(this, "Se debe ingresar un código para la maquinaria");
            txt_codigo_maquinaria.requestFocus();
            return;
        }
        if (txt_descripcion_maquinaria.getText().equals("")) {
            JOptionPane.showMessageDialog(this, "Se debe ingresar una descripción para la maquinaria");
            txt_descripcion_maquinaria.requestFocus();
            return;
        }

        //Lectura de datos
        Maquinaria dts = new Maquinaria();
        dts.setId_area(Integer.parseInt(txt_id_area.getText()));
        dts.setCodigo(txt_codigo_maquinaria.getText());
        dts.setDescripcion(txt_descripcion_maquinaria.getText());

        //Envio de datos
        ConsulMaquinaria func = new ConsulMaquinaria();
        if (accionMaquinaria.equals("guardar")) {
            if (func.insertar(dts)) {
                JOptionPane.showMessageDialog(this, "Maquinaria registrada satisfactoriamente");
                MostrarMaquinarias();
                InhabilitarMaquinaria();
            }
        } else if (accionMaquinaria.equals("editar")) {
            dts.setId(Integer.parseInt(txt_id_maquinaria.getText()));
            if (func.editar(dts)) {
                JOptionPane.showMessageDialog(this, "Maquinaria editada satisfactoriamente");
                MostrarMaquinarias();
                InhabilitarMaquinaria();
            }
        }
    }//GEN-LAST:event_btn_guardar_maquinariaActionPerformed

    private void btn_eliminar_maquinariaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_eliminar_maquinariaActionPerformed
        if (!txt_id_maquinaria.getText().equals("")) {
            //Lectura y obtencion de datos
            Maquinaria dts = new ConsulMaquinaria().obtener(Integer.parseInt(txt_id_maquinaria.getText()));
            //La maquinaria tiene maquinas?
            if (new ConsulMaquina().hayMaquina(dts)) {
                String msg = "Esta maquinaria no se puede eliminar\n"
                        + "Hay maquinas registradas de esta maquinaria";
                JOptionPane.showMessageDialog(this, msg);
                return;
            }
            //La maquinaria tiene mantenimientos?
            if (new ConsulMantenimiento().hayMantenimientos(dts)) {
                String msg = "Esta maquinaria no se puede eliminar\n"
                        + "Hay mantenimientos registrados de esta maquinaria";
                JOptionPane.showMessageDialog(this, msg);
                return;
            }
            //Confirmacion
            int confirmacion = JOptionPane.showConfirmDialog(this, "¿Estás seguro de eliminar la maquinaria?", "Confirmar", 2);
            if (confirmacion == 0) {
                //Envio de datos
                ConsulMaquinaria func = new ConsulMaquinaria();
                if (func.eliminar(dts)) {
                    JOptionPane.showMessageDialog(this, "Maquinaria eliminada satisfactoriamente");
                    MostrarMaquinarias();
                    InhabilitarMaquinaria();
                }
            }
        }
    }//GEN-LAST:event_btn_eliminar_maquinariaActionPerformed

    private void btn_guardar_maquinaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_guardar_maquinaActionPerformed
        //Validacion de datos
        if (txt_id_maquinaria2.getText().equals("")) {
            JOptionPane.showMessageDialog(this, "Se debe seleccionar la maquinaria para la maquina");
            return;
        }
        if (txt_codigo_maquina.getText().equals("")) {
            JOptionPane.showMessageDialog(this, "Se debe ingresar un código para la maquina");
            txt_codigo_maquina.requestFocus();
            return;
        }
        if (txt_nombre_maquina.getText().equals("")) {
            JOptionPane.showMessageDialog(this, "Se debe ingresar un nombre para la maquina");
            txt_nombre_maquina.requestFocus();
            return;
        }

        //Lectura de datos
        Maquina dts = new Maquina();
        dts.setId_maquinaria(Integer.parseInt(txt_id_maquinaria2.getText()));
        dts.setCodigo(txt_codigo_maquina.getText());
        dts.setNombre(txt_nombre_maquina.getText());

        //Envio de datos
        ConsulMaquina func = new ConsulMaquina();
        if (accionMaquina.equals("guardar")) {
            if (func.insertar(dts)) {
                JOptionPane.showMessageDialog(this, "Maquina registrada satisfactoriamente");
                MostrarMaquinas();
                InhabilitarMaquina();
            }
        } else if (accionMaquina.equals("editar")) {
            dts.setId(Integer.parseInt(txt_id_maquina.getText()));
            if (func.editar(dts)) {
                JOptionPane.showMessageDialog(this, "Maquina editada satisfactoriamente");
                MostrarMaquinas();
                InhabilitarMaquina();
            }
        }
    }//GEN-LAST:event_btn_guardar_maquinaActionPerformed

    private void btn_eliminar_maquinaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_eliminar_maquinaActionPerformed
        if (!txt_id_maquina.getText().equals("")) {
            //Lectura y obtencion de datos
            Maquina dts = new ConsulMaquina().obtener(Integer.parseInt(txt_id_maquina.getText()));
            //La maquina tiene agendas
            if (new ConsulAgenda().hayAgenda(dts)) {
                String msg = "Esta maquina no se puede eliminar\n"
                        + "Hay agendas registradas de esta maquina";
                JOptionPane.showMessageDialog(this, msg);
                return;
            }
            //Confirmacion
            int confirmacion = JOptionPane.showConfirmDialog(this, "¿Estás seguro de eliminar la maquina?", "Confirmar", 2);
            if (confirmacion == 0) {
                //Envio de datos
                ConsulMaquina func = new ConsulMaquina();
                if (func.eliminar(dts)) {
                    JOptionPane.showMessageDialog(this, "Maquina eliminada satisfactoriamente");
                    MostrarMaquinas();
                    InhabilitarMaquina();
                }
            }
        }
    }//GEN-LAST:event_btn_eliminar_maquinaActionPerformed

    private void btn_buscar_areaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_buscar_areaActionPerformed
        frm_buscar_areas form = new frm_buscar_areas();
        form.toFront();
        form.setVisible(true);
    }//GEN-LAST:event_btn_buscar_areaActionPerformed

    private void btn_nuevo_maquinariaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_nuevo_maquinariaActionPerformed
        HabilitarMaquinaria();
        btn_guardar_maquinaria.setText("Guardar");
        accionMaquinaria = "guardar";
    }//GEN-LAST:event_btn_nuevo_maquinariaActionPerformed

    private void cmb_areasItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cmb_areasItemStateChanged
        MostrarMaquinarias();
        ListaMaquinarias();
    }//GEN-LAST:event_cmb_areasItemStateChanged

    private void btn_gestionar_areasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_gestionar_areasActionPerformed
        frm_areas.ventana = "MAQ";
        new frm_areas().setVisible(true);
    }//GEN-LAST:event_btn_gestionar_areasActionPerformed

    private void tab_maquinariasMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tab_maquinariasMouseClicked
        //Habilitacion de campos de maquinaria
        btn_guardar_maquinaria.setText("Editar");
        HabilitarMaquinaria();
        btn_eliminar_maquinaria.setEnabled(true);
        accionMaquinaria = "editar";
        
        //Rellenado de campos maquinaria
        int fila = tab_maquinarias.rowAtPoint(evt.getPoint());
        txt_id_maquinaria.setText(tab_maquinarias.getValueAt(fila, 0).toString());
        txt_id_area.setText(tab_maquinarias.getValueAt(fila, 1).toString());
        txt_nombre_area.setText(tab_maquinarias.getValueAt(fila, 2).toString());
        txt_codigo_maquinaria.setText(tab_maquinarias.getValueAt(fila, 3).toString());
        txt_descripcion_maquinaria.setText(tab_maquinarias.getValueAt(fila, 4).toString());
        
        //Rellenado de campos maquina
        txt_id_maquinaria2.setText(tab_maquinarias.getValueAt(fila, 0).toString());
        txt_codigo_maquinaria2.setText(tab_maquinarias.getValueAt(fila, 3).toString());
        
    }//GEN-LAST:event_tab_maquinariasMouseClicked

    private void btn_nuevo_maquinaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_nuevo_maquinaActionPerformed
        HabilitarMaquina();
        btn_guardar_maquina.setText("Guardar");
        accionMaquina = "guardar";
    }//GEN-LAST:event_btn_nuevo_maquinaActionPerformed

    private void cmb_maquinariasItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cmb_maquinariasItemStateChanged
        MostrarMaquinas();
    }//GEN-LAST:event_cmb_maquinariasItemStateChanged

    private void tab_maquinasMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tab_maquinasMouseClicked
        //Habilitacion de campos maquina
        btn_guardar_maquina.setText("Editar");
        HabilitarMaquina();
        btn_eliminar_maquina.setEnabled(true);
        accionMaquina = "editar";
        
        //Rellenado de campos maquina
        int fila = tab_maquinas.rowAtPoint(evt.getPoint());
        txt_id_maquina.setText(tab_maquinas.getValueAt(fila, 0).toString());
        txt_codigo_maquina.setText(tab_maquinas.getValueAt(fila, 1).toString());
        txt_nombre_maquina.setText(tab_maquinas.getValueAt(fila, 2).toString());
        txt_id_maquinaria2.setText(tab_maquinas.getValueAt(fila, 3).toString());
        txt_codigo_maquinaria2.setText(tab_maquinas.getValueAt(fila, 4).toString());
    }//GEN-LAST:event_tab_maquinasMouseClicked

    private void formWindowClosed(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosed

        switch (ventana) {
            case "MP" -> { //Si lo abrió el gestionador de mantenimientos preventivos
                frm_mant_prev.ListaAreas();
                frm_mant_prev.cmb_areas.setSelectedIndex(0);
                frm_mant_prev.ListaMaquinarias();
                frm_mant_prev.cmb_maquinarias.setSelectedIndex(0);
                frm_mant_prev.MostrarMantenimientos();
                ventana = "";
            }
            case "MC" -> { //Si lo abrió el gestionador de mantenimientos correctivos
                frm_mant_corr.ListaAreas();
                frm_mant_corr.cmb_areas.setSelectedIndex(0);
                frm_mant_corr.ListaMaquinarias();
                frm_mant_corr.cmb_maquinarias.setSelectedIndex(0);
                frm_mant_corr.MostrarMantenimientos();
                ventana = "";
            }
            case "MN" -> { //Si lo abrió el manual
                frm_manual.ListaAreas();
                frm_manual.cmb_area.setSelectedIndex(0);
                frm_manual.ListaMaquinarias();
                frm_manual.cmb_maquinaria.setSelectedIndex(0);
                ventana = "";
            }
            default -> {
            }
        }
        ventana = "";
    }//GEN-LAST:event_formWindowClosed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frm_maquinas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frm_maquinas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frm_maquinas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frm_maquinas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frm_maquinas().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_buscar_area;
    private javax.swing.JButton btn_eliminar_maquina;
    private javax.swing.JButton btn_eliminar_maquinaria;
    private javax.swing.JButton btn_gestionar_areas;
    private javax.swing.JButton btn_guardar_maquina;
    private javax.swing.JButton btn_guardar_maquinaria;
    private javax.swing.JButton btn_nuevo_maquina;
    private javax.swing.JButton btn_nuevo_maquinaria;
    public static javax.swing.JComboBox<String> cmb_areas;
    private javax.swing.JComboBox<String> cmb_maquinarias;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JScrollPane jScrollPane_descripcion_maquinaria;
    private javax.swing.JScrollPane jScrollPane_tabla_maquina;
    private javax.swing.JScrollPane jScrollPane_tabla_maquinaria;
    private javax.swing.JLabel lbl_area;
    private javax.swing.JLabel lbl_buscar_area;
    private javax.swing.JLabel lbl_codigo_maquina;
    private javax.swing.JLabel lbl_codigo_maquinaria;
    private javax.swing.JLabel lbl_descripcion_maquinaria;
    private javax.swing.JLabel lbl_maquinaria;
    private javax.swing.JLabel lbl_nombre_maquina;
    private javax.swing.JLabel lbl_num_registros_maquina;
    private static javax.swing.JLabel lbl_num_registros_maquinaria;
    private javax.swing.JLabel lbl_titulo;
    private javax.swing.JPanel pnl_botones_maquina;
    private javax.swing.JPanel pnl_botones_maquinaria;
    private javax.swing.JPanel pnl_cabecera;
    private javax.swing.JPanel pnl_contenido;
    private javax.swing.JPanel pnl_controles_maquina;
    private javax.swing.JPanel pnl_controles_maquinaria;
    private javax.swing.JPanel pnl_pie;
    private javax.swing.JPanel pnl_sesion_info;
    private javax.swing.JPanel pnl_tabla_maquina;
    private javax.swing.JPanel pnl_tabla_maquinaria;
    private static javax.swing.JTable tab_maquinarias;
    private javax.swing.JTable tab_maquinas;
    private javax.swing.JTextField txt_codigo_maquina;
    private javax.swing.JTextField txt_codigo_maquinaria;
    private javax.swing.JTextField txt_codigo_maquinaria2;
    private javax.swing.JTextArea txt_descripcion_maquinaria;
    public static javax.swing.JTextField txt_id_area;
    private javax.swing.JTextField txt_id_maquina;
    private javax.swing.JTextField txt_id_maquinaria;
    private javax.swing.JTextField txt_id_maquinaria2;
    public static javax.swing.JTextField txt_nombre_area;
    private javax.swing.JTextField txt_nombre_maquina;
    // End of variables declaration//GEN-END:variables
}
