package ventanas;

import clases.Operario;
import consultas.ConsulEjecucion;
import consultas.ConsulOperario;
import javax.swing.JOptionPane;
import paneles.*;

public class frm_operarios extends javax.swing.JFrame {

    private String user;
    private char[] password;

    public frm_operarios() {
        initComponents();
        
        //Paneles
        pnl_sesion_info.add(new pnl_sesionde());
        pnl_pie.add(new pnl_footer());

        //Muestra los operarios registrados en la tabla
        Mostrar();
    }

    public static void Inhabilitar() {
        txt_nombre.setEnabled(false);
        txt_ap_paterno.setEnabled(false);
        txt_ap_materno.setEnabled(false);
        cmb_estado.setEnabled(false);

        txt_id_operario.setText("");
        txt_nombre.setText("");
        txt_ap_paterno.setText("");
        txt_ap_materno.setText("");

        btn_editar.setEnabled(false);
        btn_eliminar.setEnabled(false);
        btn_userpassword.setEnabled(false);
    }

    private void Habilitar() {
        txt_nombre.setEnabled(true);
        txt_ap_paterno.setEnabled(true);
        txt_ap_materno.setEnabled(true);
        cmb_estado.setEnabled(true);

        txt_id_operario.setText("");
        txt_nombre.setText("");
        txt_ap_paterno.setText("");
        txt_ap_materno.setText("");

        btn_editar.setEnabled(true);
        btn_eliminar.setEnabled(true);
        btn_userpassword.setEnabled(true);
    }

    public static void Mostrar() {
        tab_operarios.setModel(new ConsulOperario().mostrar());
        OcultarColumnas();
        lbl_num_registros.setText("Número de operarios: " + ConsulOperario.num_registros);
    }

    private static void OcultarColumnas() {
        int[] columnas = {0, 4, 5};
        for (int columna : columnas) {
            tab_operarios.getColumnModel().getColumn(columna).setMaxWidth(0);
            tab_operarios.getColumnModel().getColumn(columna).setMinWidth(0);
            tab_operarios.getColumnModel().getColumn(columna).setPreferredWidth(0);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnl_cabecera = new javax.swing.JPanel();
        lbl_titulo = new javax.swing.JLabel();
        pnl_sesion_info = new javax.swing.JPanel();
        pnl_contenido = new javax.swing.JPanel();
        pnl_controles = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        pnl_botones = new javax.swing.JPanel();
        btn_nuevo = new javax.swing.JButton();
        btn_editar = new javax.swing.JButton();
        btn_eliminar = new javax.swing.JButton();
        btn_userpassword = new javax.swing.JButton();
        txt_nombre = new javax.swing.JTextField();
        txt_id_operario = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        txt_ap_paterno = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        txt_ap_materno = new javax.swing.JTextField();
        cmb_estado = new javax.swing.JComboBox<>();
        jLabel7 = new javax.swing.JLabel();
        pnl_tabla = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tab_operarios = new javax.swing.JTable();
        lbl_num_registros = new javax.swing.JLabel();
        pnl_pie = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Gestor de operarios");
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setPreferredSize(new java.awt.Dimension(960, 480));
        setSize(new java.awt.Dimension(960, 480));

        pnl_cabecera.setBackground(new java.awt.Color(132, 129, 122));
        pnl_cabecera.setPreferredSize(new java.awt.Dimension(1280, 80));
        pnl_cabecera.setLayout(new java.awt.BorderLayout());

        lbl_titulo.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        lbl_titulo.setForeground(new java.awt.Color(255, 255, 255));
        lbl_titulo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl_titulo.setText("GESTOR DE OPERARIOS");
        pnl_cabecera.add(lbl_titulo, java.awt.BorderLayout.CENTER);

        pnl_sesion_info.setBackground(new java.awt.Color(209, 204, 192));
        pnl_sesion_info.setPreferredSize(new java.awt.Dimension(120, 80));
        pnl_sesion_info.setLayout(new java.awt.GridLayout(1, 0));
        pnl_cabecera.add(pnl_sesion_info, java.awt.BorderLayout.LINE_END);

        getContentPane().add(pnl_cabecera, java.awt.BorderLayout.PAGE_START);

        pnl_contenido.setBackground(new java.awt.Color(204, 204, 204));
        pnl_contenido.setLayout(new java.awt.GridLayout(1, 0, 4, 4));

        pnl_controles.setBackground(new java.awt.Color(255, 255, 255));

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel3.setText("Nombre:");

        pnl_botones.setLayout(new java.awt.GridLayout(2, 0, 4, 4));

        btn_nuevo.setBackground(new java.awt.Color(204, 204, 204));
        btn_nuevo.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        btn_nuevo.setText("Nuevo");
        btn_nuevo.setContentAreaFilled(false);
        btn_nuevo.setOpaque(true);
        btn_nuevo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_nuevoActionPerformed(evt);
            }
        });
        pnl_botones.add(btn_nuevo);

        btn_editar.setBackground(new java.awt.Color(204, 204, 204));
        btn_editar.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        btn_editar.setText("Editar");
        btn_editar.setContentAreaFilled(false);
        btn_editar.setEnabled(false);
        btn_editar.setOpaque(true);
        btn_editar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_editarActionPerformed(evt);
            }
        });
        pnl_botones.add(btn_editar);

        btn_eliminar.setBackground(new java.awt.Color(204, 204, 204));
        btn_eliminar.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        btn_eliminar.setText("Eliminar");
        btn_eliminar.setContentAreaFilled(false);
        btn_eliminar.setEnabled(false);
        btn_eliminar.setOpaque(true);
        btn_eliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_eliminarActionPerformed(evt);
            }
        });
        pnl_botones.add(btn_eliminar);

        btn_userpassword.setBackground(new java.awt.Color(204, 204, 204));
        btn_userpassword.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        btn_userpassword.setText("User/Pass");
        btn_userpassword.setContentAreaFilled(false);
        btn_userpassword.setEnabled(false);
        btn_userpassword.setOpaque(true);
        btn_userpassword.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_userpasswordActionPerformed(evt);
            }
        });
        pnl_botones.add(btn_userpassword);

        txt_nombre.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txt_nombre.setEnabled(false);

        txt_id_operario.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txt_id_operario.setEnabled(false);

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel5.setText("Ap. paterno:");

        txt_ap_paterno.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txt_ap_paterno.setEnabled(false);

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel6.setText("Ap. materno:");

        txt_ap_materno.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txt_ap_materno.setEnabled(false);

        cmb_estado.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Habilitado", "Inhabilitado" }));
        cmb_estado.setEnabled(false);

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel7.setText("Estado:");

        javax.swing.GroupLayout pnl_controlesLayout = new javax.swing.GroupLayout(pnl_controles);
        pnl_controles.setLayout(pnl_controlesLayout);
        pnl_controlesLayout.setHorizontalGroup(
            pnl_controlesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnl_controlesLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnl_controlesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(pnl_botones, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(pnl_controlesLayout.createSequentialGroup()
                        .addGroup(pnl_controlesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addComponent(jLabel5))
                        .addGap(22, 22, 22)
                        .addGroup(pnl_controlesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txt_nombre, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(txt_ap_paterno)
                            .addGroup(pnl_controlesLayout.createSequentialGroup()
                                .addComponent(txt_id_operario, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE))))
                    .addGroup(pnl_controlesLayout.createSequentialGroup()
                        .addGroup(pnl_controlesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel6)
                            .addComponent(jLabel7))
                        .addGap(18, 18, 18)
                        .addGroup(pnl_controlesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txt_ap_materno)
                            .addGroup(pnl_controlesLayout.createSequentialGroup()
                                .addComponent(cmb_estado, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE)))))
                .addContainerGap())
        );
        pnl_controlesLayout.setVerticalGroup(
            pnl_controlesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnl_controlesLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(txt_id_operario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnl_controlesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txt_nombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnl_controlesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(txt_ap_paterno, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnl_controlesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(txt_ap_materno, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnl_controlesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cmb_estado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 51, Short.MAX_VALUE)
                .addComponent(pnl_botones, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pnl_contenido.add(pnl_controles);

        pnl_tabla.setBackground(new java.awt.Color(255, 255, 255));

        tab_operarios.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tab_operarios.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tab_operariosMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tab_operarios);

        lbl_num_registros.setText("Número de operarios:");

        javax.swing.GroupLayout pnl_tablaLayout = new javax.swing.GroupLayout(pnl_tabla);
        pnl_tabla.setLayout(pnl_tablaLayout);
        pnl_tablaLayout.setHorizontalGroup(
            pnl_tablaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnl_tablaLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnl_tablaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 458, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnl_tablaLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(lbl_num_registros)))
                .addContainerGap())
        );
        pnl_tablaLayout.setVerticalGroup(
            pnl_tablaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnl_tablaLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 318, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lbl_num_registros)
                .addContainerGap())
        );

        pnl_contenido.add(pnl_tabla);

        getContentPane().add(pnl_contenido, java.awt.BorderLayout.CENTER);

        pnl_pie.setBackground(new java.awt.Color(82, 190, 128));
        pnl_pie.setPreferredSize(new java.awt.Dimension(1280, 40));
        pnl_pie.setLayout(new java.awt.BorderLayout());
        getContentPane().add(pnl_pie, java.awt.BorderLayout.SOUTH);

        setSize(new java.awt.Dimension(976, 519));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btn_editarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_editarActionPerformed
        //Validacion de datos
        if (txt_nombre.getText().equals("")) {
            JOptionPane.showMessageDialog(this, "El operario no puede tener un nombre vacio");
            txt_nombre.requestFocus();
            return;
        }
        if (txt_ap_paterno.getText().equals("")) {
            JOptionPane.showMessageDialog(this, "El operario no puede tener un apellido paterno vacio");
            txt_ap_paterno.requestFocus();
            return;
        }
        if (txt_ap_materno.getText().equals("")) {
            JOptionPane.showMessageDialog(this, "El operario no puede tener un apellido materno vacio");
            txt_ap_materno.requestFocus();
            return;
        }

        //Lectura de datos
        Operario dts = new Operario();
        dts.setId(Integer.parseInt(txt_id_operario.getText()));
        dts.setNombre(txt_nombre.getText());
        dts.setAp_paterno(txt_ap_paterno.getText());
        dts.setAp_materno(txt_ap_materno.getText());
        dts.setEstado(cmb_estado.getSelectedItem().toString());

        //Verificando la no inhabilitación de una cuenta actualmente usada
        boolean cerrar = false;
        if (dts.getEstado().equals("Inhabilitado")) {
            int confirmacion = JOptionPane.showConfirmDialog(this, "Está seguro de inhabilitar su propia cuenta "
                    + "(se cerrará el programa):", "Confirmar", 2);
            if (confirmacion == 0) {
                cerrar = true;
            } else {
                return;
            }
        }

        //Envio de datos
        ConsulOperario func = new ConsulOperario();
        if (func.editarPublico(dts)) {
            JOptionPane.showMessageDialog(this, "Datos públicos del operario editados satisfactoriamente");
            //Actualiza los datos si el usuario cambión sus propios datos
            if (dts.getId() == ConsulOperario.USUARIO.getId()) {
                new ConsulOperario().actualizarUsuario();
                pnl_sesionde.Mostrar();
            }
            //Cierra el programa si se inhabilito la cuenta del mismo usuario
            if (cerrar) {
                System.exit(0);
            }
            Mostrar();
            Inhabilitar();
        }
    }//GEN-LAST:event_btn_editarActionPerformed

    private void btn_eliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_eliminarActionPerformed
        if (!txt_id_operario.getText().equals("")) {
            //Lectura y obtencion de datos
            Operario dts = new ConsulOperario().obtener(Integer.parseInt(txt_id_operario.getText()));
            //El operario tiene ejecuciones realizadas
            if (new ConsulEjecucion().numEjecuciones(dts) > 0) {
                String msg = "Este operario no se puede eliminar\n"
                        + "Hay ejecuciones registradas de este operario\n"
                        + "Recuerde que puede inhabilitar la cuenta del operario";
                JOptionPane.showMessageDialog(this, msg);
                return;
            }
            //Confirmacion
            int confirmacion = JOptionPane.showConfirmDialog(this, "¿Estás seguro de eliminar al operario?", "Confirmar", 2);
            if (confirmacion == 0) {
                //Envio de datos
                ConsulOperario func = new ConsulOperario();
                if (func.eliminar(dts)) {
                    JOptionPane.showMessageDialog(this, "Operario eliminada satisfactoriamente");
                    Mostrar();
                    Inhabilitar();
                }
            }
        }
    }//GEN-LAST:event_btn_eliminarActionPerformed

    private void btn_nuevoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_nuevoActionPerformed
        new frm_nuevo_operario().setVisible(true);
    }//GEN-LAST:event_btn_nuevoActionPerformed

    private void tab_operariosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tab_operariosMouseClicked
        //Habilita los campos
        Habilitar();
        //Rellena los campos y las variables
        int fila = tab_operarios.rowAtPoint(evt.getPoint());
        txt_id_operario.setText(tab_operarios.getValueAt(fila, 0).toString());
        txt_nombre.setText(tab_operarios.getValueAt(fila, 1).toString());
        txt_ap_paterno.setText(tab_operarios.getValueAt(fila, 2).toString());
        txt_ap_materno.setText(tab_operarios.getValueAt(fila, 3).toString());
        user = tab_operarios.getValueAt(fila, 4).toString();
        password = tab_operarios.getValueAt(fila, 5).toString().toCharArray();
        cmb_estado.setSelectedItem(tab_operarios.getValueAt(fila, 6));

    }//GEN-LAST:event_tab_operariosMouseClicked

    private void btn_userpasswordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_userpasswordActionPerformed
        frm_userpassword form = new frm_userpassword();
        form.id_op = Integer.parseInt(txt_id_operario.getText());
        form.txt_user.setText(user);
        form.password_op = password;
        form.setVisible(true);
    }//GEN-LAST:event_btn_userpasswordActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frm_operarios.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frm_operarios.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frm_operarios.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frm_operarios.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frm_operarios().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private static javax.swing.JButton btn_editar;
    private static javax.swing.JButton btn_eliminar;
    private javax.swing.JButton btn_nuevo;
    private static javax.swing.JButton btn_userpassword;
    private static javax.swing.JComboBox<String> cmb_estado;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JScrollPane jScrollPane1;
    private static javax.swing.JLabel lbl_num_registros;
    private javax.swing.JLabel lbl_titulo;
    private javax.swing.JPanel pnl_botones;
    private javax.swing.JPanel pnl_cabecera;
    private javax.swing.JPanel pnl_contenido;
    private javax.swing.JPanel pnl_controles;
    private javax.swing.JPanel pnl_pie;
    private javax.swing.JPanel pnl_sesion_info;
    private javax.swing.JPanel pnl_tabla;
    private static javax.swing.JTable tab_operarios;
    private static javax.swing.JTextField txt_ap_materno;
    private static javax.swing.JTextField txt_ap_paterno;
    private static javax.swing.JTextField txt_id_operario;
    private static javax.swing.JTextField txt_nombre;
    // End of variables declaration//GEN-END:variables
}
