package ventanas;

import consultas.Auxiliar;
import consultas.ConsulAgenda;
import consultas.ConsulArea;
import consultas.ConsulMaquinaria;
import java.sql.Date;
import javax.swing.JOptionPane;
import paneles.*;

public class frm_menu_principal extends javax.swing.JFrame {

    public frm_menu_principal() {
        initComponents();

        //Paneles
        pnl_sesion_info.add(new pnl_sesionde());
        pnl_pie.add(new pnl_footer());

        //Rellena los combobox
        ListaAreas();
        ListaMaquinarias();

        //Pone la fecha de hoy
        dtc_fecha1.setDate(new java.util.Date());
        dtc_fecha2.setDate(new java.util.Date());

        //Muestralas agendas de la fecha indicada
        Mostrar();
    }

    //Escribe las areas registradas en el combobox
    private void ListaAreas() {
        cmb_area.setModel(new ConsulArea().lista());
    }

    //Escribe las maquinarias registradas en el combobox
    private void ListaMaquinarias() {
        cmb_maquinaria.setModel(new ConsulMaquinaria().lista(cmb_area.getSelectedItem().toString()));
    }

    //Muestra los mantenimientos de hoy
    public static void Mostrar() {
        String area = cmb_area.getSelectedItem().toString();
        String maquinaria = cmb_maquinaria.getSelectedItem().toString();
        Date fecha1 = Auxiliar.SQLDate(dtc_fecha1.getCalendar());
        Date fecha2 = Auxiliar.SQLDate(dtc_fecha2.getCalendar());
        tab_pendientes.setModel(new ConsulAgenda().mostrarPendientes(area, maquinaria, fecha1, fecha2));
        OcultarColumnas();
        lbl_num_registros.setText("Número de tareas pedientes: " + ConsulAgenda.num_registros);
    }

    private static void OcultarColumnas() {
        int[] columnas = {0, 1, 3, 4, 6};
        for (int columna : columnas) {
            tab_pendientes.getColumnModel().getColumn(columna).setMaxWidth(0);
            tab_pendientes.getColumnModel().getColumn(columna).setMinWidth(0);
            tab_pendientes.getColumnModel().getColumn(columna).setPreferredWidth(0);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnl_cabecera = new javax.swing.JPanel();
        lbl_titulo = new javax.swing.JLabel();
        pnl_sesion_info = new javax.swing.JPanel();
        pnl_contenido = new javax.swing.JPanel();
        pnl_botones = new javax.swing.JPanel();
        btn_areas = new javax.swing.JButton();
        btn_maquinas = new javax.swing.JButton();
        btn_preventivos = new javax.swing.JButton();
        btn_correctivos = new javax.swing.JButton();
        btn_manual = new javax.swing.JButton();
        btn_agendas = new javax.swing.JButton();
        btn_ejecuciones = new javax.swing.JButton();
        btn_dias_trabajo = new javax.swing.JButton();
        btn_usuarios = new javax.swing.JButton();
        pnl_hoy = new javax.swing.JPanel();
        lbl_mp_a_realizar = new javax.swing.JLabel();
        lbl_area = new javax.swing.JLabel();
        cmb_area = new javax.swing.JComboBox<>();
        lbl_maquinaria = new javax.swing.JLabel();
        cmb_maquinaria = new javax.swing.JComboBox<>();
        lbl_fecha1 = new javax.swing.JLabel();
        dtc_fecha1 = new com.toedter.calendar.JDateChooser();
        lbl_fecha2 = new javax.swing.JLabel();
        dtc_fecha2 = new com.toedter.calendar.JDateChooser();
        btn_hoy = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tab_pendientes = new javax.swing.JTable();
        lbl_num_registros = new javax.swing.JLabel();
        pnl_pie = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Menu principal");
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setSize(new java.awt.Dimension(1280, 640));
        getContentPane().setLayout(new java.awt.BorderLayout(0, 4));

        pnl_cabecera.setBackground(new java.awt.Color(205, 97, 51));
        pnl_cabecera.setPreferredSize(new java.awt.Dimension(1280, 80));
        pnl_cabecera.setLayout(new java.awt.BorderLayout());

        lbl_titulo.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        lbl_titulo.setForeground(new java.awt.Color(255, 255, 255));
        lbl_titulo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl_titulo.setText("GESTOR DE MANTENIMIENTO - SAITO MAINTENANCE");
        pnl_cabecera.add(lbl_titulo, java.awt.BorderLayout.CENTER);

        pnl_sesion_info.setBackground(new java.awt.Color(255, 121, 63));
        pnl_sesion_info.setPreferredSize(new java.awt.Dimension(120, 80));
        pnl_sesion_info.setLayout(new java.awt.GridLayout(1, 0));
        pnl_cabecera.add(pnl_sesion_info, java.awt.BorderLayout.LINE_END);

        getContentPane().add(pnl_cabecera, java.awt.BorderLayout.PAGE_START);

        pnl_contenido.setBackground(new java.awt.Color(204, 204, 204));
        pnl_contenido.setLayout(new java.awt.GridLayout(1, 0, 4, 4));

        pnl_botones.setLayout(new java.awt.GridLayout(0, 1, 0, 4));

        btn_areas.setBackground(new java.awt.Color(255, 255, 255));
        btn_areas.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btn_areas.setForeground(new java.awt.Color(179, 57, 57));
        btn_areas.setText("GESTIONAR AREAS");
        btn_areas.setContentAreaFilled(false);
        btn_areas.setOpaque(true);
        btn_areas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_areasActionPerformed(evt);
            }
        });
        pnl_botones.add(btn_areas);

        btn_maquinas.setBackground(new java.awt.Color(255, 255, 255));
        btn_maquinas.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btn_maquinas.setForeground(new java.awt.Color(34, 112, 147));
        btn_maquinas.setText("GESTIONAR MAQUINAS");
        btn_maquinas.setContentAreaFilled(false);
        btn_maquinas.setOpaque(true);
        btn_maquinas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_maquinasActionPerformed(evt);
            }
        });
        pnl_botones.add(btn_maquinas);

        btn_preventivos.setBackground(new java.awt.Color(255, 255, 255));
        btn_preventivos.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btn_preventivos.setForeground(new java.awt.Color(33, 140, 116));
        btn_preventivos.setText("GESTIONAR MANTENIMIENTOS PREVENTIVOS");
        btn_preventivos.setContentAreaFilled(false);
        btn_preventivos.setOpaque(true);
        btn_preventivos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_preventivosActionPerformed(evt);
            }
        });
        pnl_botones.add(btn_preventivos);

        btn_correctivos.setBackground(new java.awt.Color(255, 255, 255));
        btn_correctivos.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btn_correctivos.setForeground(new java.awt.Color(33, 140, 116));
        btn_correctivos.setText("GESTIONAR MANTENIMIENTOS CORRECTIVOS");
        btn_correctivos.setContentAreaFilled(false);
        btn_correctivos.setOpaque(true);
        btn_correctivos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_correctivosActionPerformed(evt);
            }
        });
        pnl_botones.add(btn_correctivos);

        btn_manual.setBackground(new java.awt.Color(255, 255, 255));
        btn_manual.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btn_manual.setForeground(new java.awt.Color(204, 142, 53));
        btn_manual.setText("MANUAL DE MANTENIMIENTOS");
        btn_manual.setContentAreaFilled(false);
        btn_manual.setOpaque(true);
        btn_manual.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_manualActionPerformed(evt);
            }
        });
        pnl_botones.add(btn_manual);

        btn_agendas.setBackground(new java.awt.Color(255, 255, 255));
        btn_agendas.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btn_agendas.setForeground(new java.awt.Color(71, 71, 135));
        btn_agendas.setText("GESTIONAR AGENDAS");
        btn_agendas.setContentAreaFilled(false);
        btn_agendas.setOpaque(true);
        btn_agendas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_agendasActionPerformed(evt);
            }
        });
        pnl_botones.add(btn_agendas);

        btn_ejecuciones.setBackground(new java.awt.Color(255, 255, 255));
        btn_ejecuciones.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btn_ejecuciones.setForeground(new java.awt.Color(34, 112, 147));
        btn_ejecuciones.setText("GESTIONAR EJECUCIONES");
        btn_ejecuciones.setContentAreaFilled(false);
        btn_ejecuciones.setOpaque(true);
        btn_ejecuciones.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_ejecucionesActionPerformed(evt);
            }
        });
        pnl_botones.add(btn_ejecuciones);

        btn_dias_trabajo.setBackground(new java.awt.Color(255, 255, 255));
        btn_dias_trabajo.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btn_dias_trabajo.setForeground(new java.awt.Color(71, 71, 135));
        btn_dias_trabajo.setText("GESTIONAR DIAS DE TRABAJO");
        btn_dias_trabajo.setContentAreaFilled(false);
        btn_dias_trabajo.setOpaque(true);
        btn_dias_trabajo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_dias_trabajoActionPerformed(evt);
            }
        });
        pnl_botones.add(btn_dias_trabajo);

        btn_usuarios.setBackground(new java.awt.Color(255, 255, 255));
        btn_usuarios.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btn_usuarios.setForeground(new java.awt.Color(153, 153, 153));
        btn_usuarios.setText("GESTIONAR OPERARIOS");
        btn_usuarios.setContentAreaFilled(false);
        btn_usuarios.setOpaque(true);
        btn_usuarios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_usuariosActionPerformed(evt);
            }
        });
        pnl_botones.add(btn_usuarios);

        pnl_contenido.add(pnl_botones);

        pnl_hoy.setBackground(new java.awt.Color(255, 255, 255));

        lbl_mp_a_realizar.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lbl_mp_a_realizar.setForeground(new java.awt.Color(205, 97, 51));
        lbl_mp_a_realizar.setText("Mantenimiento preventivo a realizar:");

        lbl_area.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lbl_area.setText("Area:");

        cmb_area.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cmb_areaItemStateChanged(evt);
            }
        });

        lbl_maquinaria.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lbl_maquinaria.setText("Máquinaria:");

        cmb_maquinaria.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cmb_maquinariaItemStateChanged(evt);
            }
        });

        lbl_fecha1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lbl_fecha1.setText("Desde:");

        dtc_fecha1.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                dtc_fecha1PropertyChange(evt);
            }
        });

        lbl_fecha2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lbl_fecha2.setText("Hasta:");

        dtc_fecha2.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                dtc_fecha2PropertyChange(evt);
            }
        });

        btn_hoy.setText("Tareas de hoy");
        btn_hoy.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_hoyActionPerformed(evt);
            }
        });

        tab_pendientes.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tab_pendientes.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                tab_pendientesMousePressed(evt);
            }
        });
        jScrollPane1.setViewportView(tab_pendientes);

        lbl_num_registros.setText("Número de tareas pendientes:");

        javax.swing.GroupLayout pnl_hoyLayout = new javax.swing.GroupLayout(pnl_hoy);
        pnl_hoy.setLayout(pnl_hoyLayout);
        pnl_hoyLayout.setHorizontalGroup(
            pnl_hoyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnl_hoyLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnl_hoyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 618, Short.MAX_VALUE)
                    .addGroup(pnl_hoyLayout.createSequentialGroup()
                        .addGroup(pnl_hoyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lbl_area)
                            .addComponent(lbl_maquinaria))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(pnl_hoyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(cmb_area, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(cmb_maquinaria, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnl_hoyLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(lbl_num_registros))
                    .addGroup(pnl_hoyLayout.createSequentialGroup()
                        .addComponent(lbl_mp_a_realizar)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(pnl_hoyLayout.createSequentialGroup()
                        .addComponent(lbl_fecha1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(dtc_fecha1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(18, 18, 18)
                        .addComponent(lbl_fecha2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(dtc_fecha2, javax.swing.GroupLayout.PREFERRED_SIZE, 201, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btn_hoy)))
                .addContainerGap())
        );
        pnl_hoyLayout.setVerticalGroup(
            pnl_hoyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnl_hoyLayout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(lbl_mp_a_realizar)
                .addGap(18, 18, 18)
                .addGroup(pnl_hoyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(pnl_hoyLayout.createSequentialGroup()
                        .addGroup(pnl_hoyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(cmb_area, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lbl_area))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(pnl_hoyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(cmb_maquinaria, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lbl_maquinaria))
                        .addGroup(pnl_hoyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnl_hoyLayout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(pnl_hoyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(dtc_fecha1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lbl_fecha1, javax.swing.GroupLayout.Alignment.TRAILING)))
                            .addGroup(pnl_hoyLayout.createSequentialGroup()
                                .addGap(9, 9, 9)
                                .addGroup(pnl_hoyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(btn_hoy)
                                    .addComponent(dtc_fecha2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                    .addComponent(lbl_fecha2))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 332, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lbl_num_registros)
                .addContainerGap())
        );

        pnl_contenido.add(pnl_hoy);

        getContentPane().add(pnl_contenido, java.awt.BorderLayout.CENTER);

        pnl_pie.setBackground(new java.awt.Color(82, 190, 128));
        pnl_pie.setPreferredSize(new java.awt.Dimension(1280, 40));
        pnl_pie.setLayout(new java.awt.BorderLayout());
        getContentPane().add(pnl_pie, java.awt.BorderLayout.SOUTH);

        setSize(new java.awt.Dimension(1296, 679));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btn_areasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_areasActionPerformed
        new frm_areas().setVisible(true);
    }//GEN-LAST:event_btn_areasActionPerformed

    private void btn_maquinasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_maquinasActionPerformed
        frm_maquinas.ventana = "";
        new frm_maquinas().setVisible(true);
    }//GEN-LAST:event_btn_maquinasActionPerformed

    private void btn_preventivosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_preventivosActionPerformed
        new frm_mant_prev().setVisible(true);
    }//GEN-LAST:event_btn_preventivosActionPerformed

    private void btn_correctivosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_correctivosActionPerformed
        new frm_mant_corr().setVisible(true);
    }//GEN-LAST:event_btn_correctivosActionPerformed

    private void btn_manualActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_manualActionPerformed
        new frm_manual().setVisible(true);
    }//GEN-LAST:event_btn_manualActionPerformed

    private void cmb_areaItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cmb_areaItemStateChanged
        ListaMaquinarias();
        Mostrar();
    }//GEN-LAST:event_cmb_areaItemStateChanged

    private void cmb_maquinariaItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cmb_maquinariaItemStateChanged
        Mostrar();
    }//GEN-LAST:event_cmb_maquinariaItemStateChanged

    private void btn_agendasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_agendasActionPerformed
        new frm_agenda().setVisible(true);
    }//GEN-LAST:event_btn_agendasActionPerformed

    private void dtc_fecha1PropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_dtc_fecha1PropertyChange
        if ("date".equals(evt.getPropertyName()) && dtc_fecha2.getCalendar() != null) {
            Mostrar();
        }
    }//GEN-LAST:event_dtc_fecha1PropertyChange

    private void dtc_fecha2PropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_dtc_fecha2PropertyChange
        if ("date".equals(evt.getPropertyName()) && dtc_fecha1.getCalendar() != null) {
            Mostrar();
        }
    }//GEN-LAST:event_dtc_fecha2PropertyChange

    private void btn_usuariosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_usuariosActionPerformed
        new frm_operarios().setVisible(true);
    }//GEN-LAST:event_btn_usuariosActionPerformed

    private void btn_dias_trabajoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_dias_trabajoActionPerformed
        new frm_dias().setVisible(true);
    }//GEN-LAST:event_btn_dias_trabajoActionPerformed

    private void btn_ejecucionesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_ejecucionesActionPerformed
        new frm_ejecucion().setVisible(true);
    }//GEN-LAST:event_btn_ejecucionesActionPerformed

    private void btn_hoyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_hoyActionPerformed
        dtc_fecha1.setDate(new java.util.Date());
        dtc_fecha2.setDate(new java.util.Date());
    }//GEN-LAST:event_btn_hoyActionPerformed

    private void tab_pendientesMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tab_pendientesMousePressed

        if (evt.getClickCount() == 2) {
            int fila = tab_pendientes.getSelectedRow();
            String[] opciones = {"Ver el manual", "Registrar la ejecución"};
            int opcion = JOptionPane.showOptionDialog(this, "¿Que quiere hacer?", "Escoja una opción",
                    JOptionPane.DEFAULT_OPTION, JOptionPane.QUESTION_MESSAGE, null, opciones, null);
            if (opcion == 0) {
                new frm_manual().setVisible(true);

                frm_manual.cmb_area.setSelectedItem(cmb_area.getSelectedItem().toString());
                frm_manual.cmb_maquinaria.setSelectedItem(cmb_maquinaria.getSelectedItem().toString());

                frm_manual.txt_id_mantenimiento.setText(tab_pendientes.getValueAt(fila, 3).toString());
                frm_manual.txt_nombre_mantenimiento.setText(tab_pendientes.getValueAt(fila, 5).toString());
                frm_manual.txt_codigo_mantenimiento.setText(tab_pendientes.getValueAt(fila, 4).toString());
                frm_manual.txt_tipo_mantenimiento.setText(tab_pendientes.getValueAt(fila, 6).toString());

                frm_manual.MostrarPasos();
                frm_manual.btn_cambiar_imagen.setEnabled(false);
            } else if (opcion == 1) {
                new frm_ejecucion().setVisible(true);

                frm_ejecucion.pendiente = true;
                frm_ejecucion.Habilitar();
                frm_ejecucion.btn_guardar.setText("Guardar");
                frm_ejecucion.accion = "guardar";
                frm_ejecucion.dtc_fecha.setEnabled(true);
                frm_ejecucion.btn_buscar_maquina.setEnabled(true);
                frm_ejecucion.btn_buscar_mantenimiento.setEnabled(true);

                frm_ejecucion.txt_id_maquina.setText(tab_pendientes.getValueAt(fila, 1).toString());
                frm_ejecucion.txt_codigo_maquina.setText(tab_pendientes.getValueAt(fila, 2).toString());
                frm_ejecucion.txt_id_mantenimiento.setText(tab_pendientes.getValueAt(fila, 3).toString());
                frm_ejecucion.txt_codigo_mantenimiento.setText(tab_pendientes.getValueAt(fila, 4).toString());
                frm_ejecucion.txt_nombre_mantenimiento.setText(tab_pendientes.getValueAt(fila, 5).toString());
                frm_ejecucion.txt_tipo_mantenimiento.setText(tab_pendientes.getValueAt(fila, 6).toString());
                frm_ejecucion.dtc_fecha.setDate(Date.valueOf(tab_pendientes.getValueAt(fila, 7).toString()));
            }

        }
    }//GEN-LAST:event_tab_pendientesMousePressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frm_menu_principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frm_menu_principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frm_menu_principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frm_menu_principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frm_menu_principal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_agendas;
    private javax.swing.JButton btn_areas;
    private javax.swing.JButton btn_correctivos;
    private javax.swing.JButton btn_dias_trabajo;
    private javax.swing.JButton btn_ejecuciones;
    private javax.swing.JButton btn_hoy;
    private javax.swing.JButton btn_manual;
    private javax.swing.JButton btn_maquinas;
    private javax.swing.JButton btn_preventivos;
    private javax.swing.JButton btn_usuarios;
    private static javax.swing.JComboBox<String> cmb_area;
    private static javax.swing.JComboBox<String> cmb_maquinaria;
    private static com.toedter.calendar.JDateChooser dtc_fecha1;
    private static com.toedter.calendar.JDateChooser dtc_fecha2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lbl_area;
    private javax.swing.JLabel lbl_fecha1;
    private javax.swing.JLabel lbl_fecha2;
    private javax.swing.JLabel lbl_maquinaria;
    private javax.swing.JLabel lbl_mp_a_realizar;
    private static javax.swing.JLabel lbl_num_registros;
    private javax.swing.JLabel lbl_titulo;
    private javax.swing.JPanel pnl_botones;
    private javax.swing.JPanel pnl_cabecera;
    private javax.swing.JPanel pnl_contenido;
    private javax.swing.JPanel pnl_hoy;
    private javax.swing.JPanel pnl_pie;
    private javax.swing.JPanel pnl_sesion_info;
    private static javax.swing.JTable tab_pendientes;
    // End of variables declaration//GEN-END:variables
}
