package ventanas;

import consultas.ConsulOperario;

public class frm_buscar_operarios extends javax.swing.JFrame {

    public frm_buscar_operarios() {
        initComponents();
        
        //Muestra los operarios registrados en la tabla
        Mostrar();
    }

    public static void Mostrar() {
        tab_operarios.setModel(new ConsulOperario().mostrar());
        OcultarColumnas();
        lbl_num_registros.setText("Número de operarios: " + ConsulOperario.num_registros);
    }

    private static void OcultarColumnas() {
        int[] columnas = {0, 4, 5};
        for (int columna : columnas) {
            tab_operarios.getColumnModel().getColumn(columna).setMaxWidth(0);
            tab_operarios.getColumnModel().getColumn(columna).setMinWidth(0);
            tab_operarios.getColumnModel().getColumn(columna).setPreferredWidth(0);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnl_tabla = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tab_operarios = new javax.swing.JTable();
        lbl_num_registros = new javax.swing.JLabel();
        lbl_buscar_operario = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Buscar operarios");
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setSize(new java.awt.Dimension(640, 640));

        pnl_tabla.setBackground(new java.awt.Color(255, 255, 255));

        tab_operarios.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tab_operarios.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                tab_operariosMousePressed(evt);
            }
        });
        jScrollPane1.setViewportView(tab_operarios);

        lbl_num_registros.setText("Número de operarios:");

        lbl_buscar_operario.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lbl_buscar_operario.setText("Buscar operario:");

        javax.swing.GroupLayout pnl_tablaLayout = new javax.swing.GroupLayout(pnl_tabla);
        pnl_tabla.setLayout(pnl_tablaLayout);
        pnl_tablaLayout.setHorizontalGroup(
            pnl_tablaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnl_tablaLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnl_tablaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 620, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnl_tablaLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(lbl_num_registros))
                    .addGroup(pnl_tablaLayout.createSequentialGroup()
                        .addComponent(lbl_buscar_operario)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        pnl_tablaLayout.setVerticalGroup(
            pnl_tablaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnl_tablaLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lbl_buscar_operario)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 575, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lbl_num_registros)
                .addContainerGap())
        );

        getContentPane().add(pnl_tabla, java.awt.BorderLayout.CENTER);

        setSize(new java.awt.Dimension(656, 679));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void tab_operariosMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tab_operariosMousePressed
        if (evt.getClickCount() == 2) {
            
            //Solo lo llama frm_ejecucion
            int fila = tab_operarios.getSelectedRow();
            frm_ejecucion.txt_id_operario.setText(tab_operarios.getValueAt(fila, 0).toString());
            String nombre = tab_operarios.getValueAt(fila, 1).toString();
            String ap_paterno = tab_operarios.getValueAt(fila, 2).toString();
            String ap_materno = tab_operarios.getValueAt(fila, 3).toString();
            frm_ejecucion.txt_nombre_operario.setText(nombre + " " + ap_paterno + " " + ap_materno);

            this.dispose();
        }
    }//GEN-LAST:event_tab_operariosMousePressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frm_buscar_operarios.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frm_buscar_operarios.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frm_buscar_operarios.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frm_buscar_operarios.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frm_buscar_operarios().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lbl_buscar_operario;
    private static javax.swing.JLabel lbl_num_registros;
    private javax.swing.JPanel pnl_tabla;
    private static javax.swing.JTable tab_operarios;
    // End of variables declaration//GEN-END:variables
}
