package ventanas;

import clases.Operario;
import consultas.ConsulOperario;
import java.util.Arrays;
import javax.swing.JOptionPane;

public class frm_nuevo_operario extends javax.swing.JFrame {

    public frm_nuevo_operario() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnl_controles = new javax.swing.JPanel();
        pnl_datos_publicos = new javax.swing.JPanel();
        lbl_nombre = new javax.swing.JLabel();
        txt_nombre = new javax.swing.JTextField();
        lbl_ap_paterno = new javax.swing.JLabel();
        txt_ap_paterno = new javax.swing.JTextField();
        lbl_ap_materno = new javax.swing.JLabel();
        txt_ap_materno = new javax.swing.JTextField();
        lbl_estado = new javax.swing.JLabel();
        cmb_estado = new javax.swing.JComboBox<>();
        pnl_datos_privados = new javax.swing.JPanel();
        lbl_user = new javax.swing.JLabel();
        txt_user = new javax.swing.JTextField();
        lbl_password1 = new javax.swing.JLabel();
        txt_newPassword1 = new javax.swing.JPasswordField();
        lbl_password2 = new javax.swing.JLabel();
        txt_newPassword2 = new javax.swing.JPasswordField();
        btn_guardar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Nuevo operario");
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setPreferredSize(new java.awt.Dimension(360, 390));
        setSize(new java.awt.Dimension(360, 390));

        pnl_controles.setBackground(new java.awt.Color(255, 255, 255));

        pnl_datos_publicos.setBackground(new java.awt.Color(255, 255, 255));
        pnl_datos_publicos.setBorder(javax.swing.BorderFactory.createTitledBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 153, 0), 4, true), "Datos públicos", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 11), new java.awt.Color(0, 153, 0))); // NOI18N

        lbl_nombre.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lbl_nombre.setText("Nombre:");

        txt_nombre.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        lbl_ap_paterno.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lbl_ap_paterno.setText("Ap. paterno:");

        txt_ap_paterno.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        lbl_ap_materno.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lbl_ap_materno.setText("Ap. materno:");

        txt_ap_materno.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        lbl_estado.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lbl_estado.setText("Estado:");

        cmb_estado.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Habilitado", "Inhabilitado" }));

        javax.swing.GroupLayout pnl_datos_publicosLayout = new javax.swing.GroupLayout(pnl_datos_publicos);
        pnl_datos_publicos.setLayout(pnl_datos_publicosLayout);
        pnl_datos_publicosLayout.setHorizontalGroup(
            pnl_datos_publicosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnl_datos_publicosLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnl_datos_publicosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lbl_nombre)
                    .addComponent(lbl_ap_paterno)
                    .addComponent(lbl_ap_materno)
                    .addComponent(lbl_estado))
                .addGap(18, 18, 18)
                .addGroup(pnl_datos_publicosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(txt_nombre)
                    .addComponent(txt_ap_paterno, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txt_ap_materno, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(cmb_estado, javax.swing.GroupLayout.Alignment.LEADING, 0, 195, Short.MAX_VALUE))
                .addContainerGap())
        );
        pnl_datos_publicosLayout.setVerticalGroup(
            pnl_datos_publicosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnl_datos_publicosLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnl_datos_publicosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbl_nombre)
                    .addComponent(txt_nombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnl_datos_publicosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbl_ap_paterno)
                    .addComponent(txt_ap_paterno, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnl_datos_publicosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbl_ap_materno)
                    .addComponent(txt_ap_materno, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnl_datos_publicosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cmb_estado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbl_estado))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pnl_datos_privados.setBackground(new java.awt.Color(255, 255, 255));
        pnl_datos_privados.setBorder(javax.swing.BorderFactory.createTitledBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 0, 0), 4, true), "Datos privados", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 11), new java.awt.Color(255, 0, 0))); // NOI18N

        lbl_user.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lbl_user.setText("Usuario:");

        lbl_password1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lbl_password1.setText("Contraseña:");

        lbl_password2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lbl_password2.setText("Confirmar:");

        javax.swing.GroupLayout pnl_datos_privadosLayout = new javax.swing.GroupLayout(pnl_datos_privados);
        pnl_datos_privados.setLayout(pnl_datos_privadosLayout);
        pnl_datos_privadosLayout.setHorizontalGroup(
            pnl_datos_privadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnl_datos_privadosLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnl_datos_privadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lbl_password1)
                    .addComponent(lbl_user)
                    .addComponent(lbl_password2))
                .addGap(18, 18, 18)
                .addGroup(pnl_datos_privadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txt_newPassword2)
                    .addComponent(txt_user)
                    .addComponent(txt_newPassword1))
                .addGap(9, 9, 9))
        );
        pnl_datos_privadosLayout.setVerticalGroup(
            pnl_datos_privadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnl_datos_privadosLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnl_datos_privadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbl_user)
                    .addComponent(txt_user, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnl_datos_privadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbl_password1)
                    .addComponent(txt_newPassword1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnl_datos_privadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbl_password2)
                    .addComponent(txt_newPassword2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        btn_guardar.setBackground(new java.awt.Color(204, 204, 204));
        btn_guardar.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        btn_guardar.setText("Guardar");
        btn_guardar.setContentAreaFilled(false);
        btn_guardar.setOpaque(true);
        btn_guardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_guardarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnl_controlesLayout = new javax.swing.GroupLayout(pnl_controles);
        pnl_controles.setLayout(pnl_controlesLayout);
        pnl_controlesLayout.setHorizontalGroup(
            pnl_controlesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnl_controlesLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnl_controlesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(pnl_datos_privados, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(pnl_datos_publicos, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btn_guardar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        pnl_controlesLayout.setVerticalGroup(
            pnl_controlesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnl_controlesLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(pnl_datos_publicos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pnl_datos_privados, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btn_guardar, javax.swing.GroupLayout.DEFAULT_SIZE, 55, Short.MAX_VALUE)
                .addContainerGap())
        );

        getContentPane().add(pnl_controles, java.awt.BorderLayout.CENTER);

        setSize(new java.awt.Dimension(376, 399));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btn_guardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_guardarActionPerformed
        //Validacion de datos
        if (txt_nombre.getText().equals("")) {
            JOptionPane.showMessageDialog(this, "El operario no puede tener un nombre vacio");
            txt_nombre.requestFocus();
            return;
        }
        if (txt_ap_paterno.getText().equals("")) {
            JOptionPane.showMessageDialog(this, "El operario no puede tener un apellido paterno vacio");
            txt_ap_paterno.requestFocus();
            return;
        }
        if (txt_ap_materno.getText().equals("")) {
            JOptionPane.showMessageDialog(this, "El operario no puede tener un apellido materno vacio");
            txt_ap_materno.requestFocus();
            return;
        }
        if (txt_user.getText().equals("")) {
            JOptionPane.showMessageDialog(this, "Se debe ingresar un usuario");
            txt_user.requestFocus();
            return;
        }

        //Lectura de datos
        Operario dts = new Operario();
        dts.setNombre(txt_nombre.getText());
        dts.setAp_paterno(txt_ap_paterno.getText());
        dts.setAp_materno(txt_ap_materno.getText());
        dts.setEstado(cmb_estado.getSelectedItem().toString());
        dts.setUser(txt_user.getText());
        //Lectura de password
        if (Arrays.equals(txt_newPassword1.getPassword(), txt_newPassword2.getPassword())) {
            dts.setPassword(txt_newPassword1.getPassword());
        } else {
            JOptionPane.showMessageDialog(this, "Las contraseñas no son iguales");
            txt_newPassword1.setText("");
            txt_newPassword2.setText("");
            txt_newPassword1.requestFocus();
            return;
        }

        //Envio de datos
        ConsulOperario func = new ConsulOperario();
        if (func.insertar(dts)) {
            JOptionPane.showMessageDialog(this, "Operario registrado satisfactoriamente");
            frm_operarios.Mostrar();
            frm_operarios.Inhabilitar();
            this.dispose();
        }
    }//GEN-LAST:event_btn_guardarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frm_nuevo_operario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frm_nuevo_operario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frm_nuevo_operario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frm_nuevo_operario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frm_nuevo_operario().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private static javax.swing.JButton btn_guardar;
    private static javax.swing.JComboBox<String> cmb_estado;
    private javax.swing.JLabel lbl_ap_materno;
    private javax.swing.JLabel lbl_ap_paterno;
    private javax.swing.JLabel lbl_estado;
    private javax.swing.JLabel lbl_nombre;
    private javax.swing.JLabel lbl_password1;
    private javax.swing.JLabel lbl_password2;
    private javax.swing.JLabel lbl_user;
    private javax.swing.JPanel pnl_controles;
    private javax.swing.JPanel pnl_datos_privados;
    private javax.swing.JPanel pnl_datos_publicos;
    private static javax.swing.JTextField txt_ap_materno;
    private static javax.swing.JTextField txt_ap_paterno;
    private javax.swing.JPasswordField txt_newPassword1;
    private javax.swing.JPasswordField txt_newPassword2;
    private static javax.swing.JTextField txt_nombre;
    public javax.swing.JTextField txt_user;
    // End of variables declaration//GEN-END:variables
}
