package ventanas;

import clases.Agenda;
import clases.Ejecucion;
import consultas.Auxiliar;
import consultas.ConsulAgenda;
import consultas.ConsulArea;
import consultas.ConsulEjecucion;
import consultas.ConsulMaquinaria;
import consultas.ConsulOperario;
import java.sql.Date;
import java.util.Calendar;
import javax.swing.JOptionPane;
import paneles.*;

public class frm_ejecucion extends javax.swing.JFrame {

    public static String ventana = "";
    public static boolean pendiente = false;

    public static String accion = "guardar";

    public frm_ejecucion() {
        initComponents();

        //Paneles
        pnl_sesion_info.add(new pnl_sesionde());
        pnl_pie.add(new pnl_footer());

        //Rellenando los combobox
        ListaAreas();
        ListaMaquinarias();

        //Pone la fecha de hoy
        dtc_fecha1.setDate(new java.util.Date());
        dtc_fecha2.setDate(new java.util.Date());

        //Mostrar
        Mostrar();
    }

    //Escribe las areas registradas en el combobox
    public static void ListaAreas() {
        cmb_areas.setModel(new ConsulArea().lista());
    }

    //Escribe las maquinarias registradas en el combobox
    private void ListaMaquinarias() {
        cmb_maquinarias.setModel(new ConsulMaquinaria().lista(cmb_areas.getSelectedItem().toString()));
    }

    private void Inhabilitar() {
        dtc_fecha.setEnabled(false);
        txt_observaciones.setEnabled(false);

        txt_id_ejecucion.setText("");
        txt_id_maquina.setText("");
        txt_codigo_maquina.setText("");
        txt_id_mantenimiento.setText("");
        txt_codigo_mantenimiento.setText("");
        txt_nombre_mantenimiento.setText("");
        txt_tipo_mantenimiento.setText("");
        txt_id_operario.setText("");
        txt_nombre_operario.setText("");
        txt_observaciones.setText("");

        btn_buscar_maquina.setEnabled(false);
        btn_buscar_mantenimiento.setEnabled(false);
        btn_buscar_operario.setEnabled(false);
        btn_guardar.setEnabled(false);
        btn_eliminar.setEnabled(false);
    }

    public static void Habilitar() {
        dtc_fecha.setEnabled(true);
        txt_observaciones.setEnabled(true);

        txt_id_ejecucion.setText("");
        txt_id_maquina.setText("");
        txt_codigo_maquina.setText("");
        txt_id_mantenimiento.setText("");
        txt_codigo_mantenimiento.setText("");
        txt_nombre_mantenimiento.setText("");
        txt_tipo_mantenimiento.setText("");
        txt_id_operario.setText(ConsulOperario.USUARIO.getId() + "");
        String nombre_operario = ConsulOperario.USUARIO.getNombre() + " "
                + ConsulOperario.USUARIO.getAp_paterno() + " "
                + ConsulOperario.USUARIO.getAp_materno();
        txt_nombre_operario.setText(nombre_operario);
        dtc_fecha.setDate(new java.util.Date());
        txt_observaciones.setText("");

        btn_buscar_maquina.setEnabled(true);
        btn_buscar_mantenimiento.setEnabled(true);
        btn_buscar_operario.setEnabled(true);
        btn_guardar.setEnabled(true);
        btn_eliminar.setEnabled(false);
    }

    //Muestra las maquinarias segun el area
    public static void Mostrar() {
        String area = cmb_areas.getSelectedItem().toString();
        String maquinaria = cmb_maquinarias.getSelectedItem().toString();
        Date fecha1 = Auxiliar.SQLDate(dtc_fecha1.getCalendar());
        Date fecha2 = Auxiliar.SQLDate(dtc_fecha2.getCalendar());
        tab_ejecuciones.setModel(new ConsulEjecucion().mostrar(area, maquinaria, fecha1, fecha2));
        OcultarColumnas();
        lbl_num_registros.setText("Número de maquinarias: " + ConsulMaquinaria.num_registros);
    }

    private static void OcultarColumnas() {
        int[] columnas = {0, 1, 3, 7};
        for (int columna : columnas) {
            tab_ejecuciones.getColumnModel().getColumn(columna).setMaxWidth(0);
            tab_ejecuciones.getColumnModel().getColumn(columna).setMinWidth(0);
            tab_ejecuciones.getColumnModel().getColumn(columna).setPreferredWidth(0);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnl_cabecera = new javax.swing.JPanel();
        lbl_titulo = new javax.swing.JLabel();
        pnl_sesion_info = new javax.swing.JPanel();
        pnl_contenido = new javax.swing.JPanel();
        pnl_controles_maquinaria = new javax.swing.JPanel();
        txt_id_ejecucion = new javax.swing.JTextField();
        lbl_maquina = new javax.swing.JLabel();
        txt_id_maquina = new javax.swing.JTextField();
        txt_codigo_maquina = new javax.swing.JTextField();
        btn_buscar_maquina = new javax.swing.JButton();
        lbl_mantenimiento = new javax.swing.JLabel();
        txt_id_mantenimiento = new javax.swing.JTextField();
        txt_codigo_mantenimiento = new javax.swing.JTextField();
        txt_nombre_mantenimiento = new javax.swing.JTextField();
        txt_tipo_mantenimiento = new javax.swing.JTextField();
        btn_buscar_mantenimiento = new javax.swing.JButton();
        lbl_operario = new javax.swing.JLabel();
        txt_id_operario = new javax.swing.JTextField();
        txt_nombre_operario = new javax.swing.JTextField();
        btn_buscar_operario = new javax.swing.JButton();
        lbl_fecha = new javax.swing.JLabel();
        dtc_fecha = new com.toedter.calendar.JDateChooser();
        lbl_observaciones = new javax.swing.JLabel();
        jScrollPane_observaciones = new javax.swing.JScrollPane();
        txt_observaciones = new javax.swing.JTextArea();
        pnl_botones = new javax.swing.JPanel();
        btn_nuevo = new javax.swing.JButton();
        btn_guardar = new javax.swing.JButton();
        btn_eliminar = new javax.swing.JButton();
        pnl_tabla = new javax.swing.JPanel();
        lbl_buscar_area = new javax.swing.JLabel();
        cmb_areas = new javax.swing.JComboBox<>();
        lbl_buscar_maquinaria = new javax.swing.JLabel();
        cmb_maquinarias = new javax.swing.JComboBox<>();
        jScrollPane_tabla_ejecucion = new javax.swing.JScrollPane();
        tab_ejecuciones = new javax.swing.JTable();
        lbl_num_registros = new javax.swing.JLabel();
        lbl_fecha1 = new javax.swing.JLabel();
        dtc_fecha1 = new com.toedter.calendar.JDateChooser();
        lbl_fecha2 = new javax.swing.JLabel();
        dtc_fecha2 = new com.toedter.calendar.JDateChooser();
        pnl_pie = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Ejecuciones");
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setSize(new java.awt.Dimension(1280, 640));
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosed(java.awt.event.WindowEvent evt) {
                formWindowClosed(evt);
            }
        });
        getContentPane().setLayout(new java.awt.BorderLayout(0, 4));

        pnl_cabecera.setBackground(new java.awt.Color(34, 112, 147));
        pnl_cabecera.setPreferredSize(new java.awt.Dimension(1280, 80));
        pnl_cabecera.setLayout(new java.awt.BorderLayout());

        lbl_titulo.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        lbl_titulo.setForeground(new java.awt.Color(255, 255, 255));
        lbl_titulo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl_titulo.setText("GESTOR DE EJECUCIONES");
        pnl_cabecera.add(lbl_titulo, java.awt.BorderLayout.CENTER);

        pnl_sesion_info.setBackground(new java.awt.Color(52, 172, 224));
        pnl_sesion_info.setPreferredSize(new java.awt.Dimension(120, 80));
        pnl_sesion_info.setLayout(new java.awt.GridLayout(1, 0));
        pnl_cabecera.add(pnl_sesion_info, java.awt.BorderLayout.LINE_END);

        getContentPane().add(pnl_cabecera, java.awt.BorderLayout.PAGE_START);

        pnl_contenido.setBackground(new java.awt.Color(204, 204, 204));
        pnl_contenido.setLayout(new java.awt.GridLayout(1, 0, 4, 4));

        pnl_controles_maquinaria.setBackground(new java.awt.Color(255, 255, 255));

        txt_id_ejecucion.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txt_id_ejecucion.setEnabled(false);

        lbl_maquina.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lbl_maquina.setText("Maquina:");

        txt_id_maquina.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txt_id_maquina.setEnabled(false);

        txt_codigo_maquina.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txt_codigo_maquina.setEnabled(false);

        btn_buscar_maquina.setText("...");
        btn_buscar_maquina.setEnabled(false);
        btn_buscar_maquina.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_buscar_maquinaActionPerformed(evt);
            }
        });

        lbl_mantenimiento.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lbl_mantenimiento.setText("Mantenimiento:");

        txt_id_mantenimiento.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txt_id_mantenimiento.setEnabled(false);

        txt_codigo_mantenimiento.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txt_codigo_mantenimiento.setEnabled(false);

        txt_nombre_mantenimiento.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txt_nombre_mantenimiento.setEnabled(false);

        txt_tipo_mantenimiento.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txt_tipo_mantenimiento.setEnabled(false);

        btn_buscar_mantenimiento.setText("...");
        btn_buscar_mantenimiento.setEnabled(false);
        btn_buscar_mantenimiento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_buscar_mantenimientoActionPerformed(evt);
            }
        });

        lbl_operario.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lbl_operario.setText("Operario:");

        txt_id_operario.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txt_id_operario.setEnabled(false);

        txt_nombre_operario.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txt_nombre_operario.setEnabled(false);

        btn_buscar_operario.setText("...");
        btn_buscar_operario.setEnabled(false);
        btn_buscar_operario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_buscar_operarioActionPerformed(evt);
            }
        });

        lbl_fecha.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lbl_fecha.setText("Fecha:");

        dtc_fecha.setEnabled(false);

        lbl_observaciones.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lbl_observaciones.setText("Observaciones:");

        txt_observaciones.setColumns(20);
        txt_observaciones.setLineWrap(true);
        txt_observaciones.setRows(4);
        txt_observaciones.setEnabled(false);
        jScrollPane_observaciones.setViewportView(txt_observaciones);

        pnl_botones.setLayout(new java.awt.GridLayout(1, 0, 4, 4));

        btn_nuevo.setBackground(new java.awt.Color(204, 204, 204));
        btn_nuevo.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btn_nuevo.setText("Nuevo");
        btn_nuevo.setContentAreaFilled(false);
        btn_nuevo.setOpaque(true);
        btn_nuevo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_nuevoActionPerformed(evt);
            }
        });
        pnl_botones.add(btn_nuevo);

        btn_guardar.setBackground(new java.awt.Color(204, 204, 204));
        btn_guardar.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btn_guardar.setText("Guardar");
        btn_guardar.setContentAreaFilled(false);
        btn_guardar.setEnabled(false);
        btn_guardar.setOpaque(true);
        btn_guardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_guardarActionPerformed(evt);
            }
        });
        pnl_botones.add(btn_guardar);

        btn_eliminar.setBackground(new java.awt.Color(204, 204, 204));
        btn_eliminar.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btn_eliminar.setText("Eliminar");
        btn_eliminar.setContentAreaFilled(false);
        btn_eliminar.setEnabled(false);
        btn_eliminar.setOpaque(true);
        btn_eliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_eliminarActionPerformed(evt);
            }
        });
        pnl_botones.add(btn_eliminar);

        javax.swing.GroupLayout pnl_controles_maquinariaLayout = new javax.swing.GroupLayout(pnl_controles_maquinaria);
        pnl_controles_maquinaria.setLayout(pnl_controles_maquinariaLayout);
        pnl_controles_maquinariaLayout.setHorizontalGroup(
            pnl_controles_maquinariaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnl_controles_maquinariaLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnl_controles_maquinariaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(pnl_botones, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(pnl_controles_maquinariaLayout.createSequentialGroup()
                        .addGroup(pnl_controles_maquinariaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lbl_operario)
                            .addComponent(lbl_mantenimiento)
                            .addComponent(lbl_fecha)
                            .addComponent(lbl_observaciones)
                            .addComponent(lbl_maquina))
                        .addGap(18, 18, 18)
                        .addGroup(pnl_controles_maquinariaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane_observaciones, javax.swing.GroupLayout.DEFAULT_SIZE, 492, Short.MAX_VALUE)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnl_controles_maquinariaLayout.createSequentialGroup()
                                .addComponent(txt_id_operario, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txt_nombre_operario)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btn_buscar_operario))
                            .addGroup(pnl_controles_maquinariaLayout.createSequentialGroup()
                                .addComponent(dtc_fecha, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(pnl_controles_maquinariaLayout.createSequentialGroup()
                                .addGroup(pnl_controles_maquinariaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(txt_id_ejecucion)
                                    .addComponent(txt_id_maquina)
                                    .addComponent(txt_id_mantenimiento, javax.swing.GroupLayout.DEFAULT_SIZE, 56, Short.MAX_VALUE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(pnl_controles_maquinariaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(pnl_controles_maquinariaLayout.createSequentialGroup()
                                        .addComponent(txt_codigo_mantenimiento, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(txt_nombre_mantenimiento)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(txt_tipo_mantenimiento, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(btn_buscar_mantenimiento))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnl_controles_maquinariaLayout.createSequentialGroup()
                                        .addComponent(txt_codigo_maquina)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(btn_buscar_maquina)))))))
                .addContainerGap())
        );
        pnl_controles_maquinariaLayout.setVerticalGroup(
            pnl_controles_maquinariaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnl_controles_maquinariaLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(txt_id_ejecucion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnl_controles_maquinariaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txt_id_maquina, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt_codigo_maquina, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbl_maquina)
                    .addComponent(btn_buscar_maquina))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnl_controles_maquinariaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txt_id_mantenimiento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt_nombre_mantenimiento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_buscar_mantenimiento)
                    .addComponent(lbl_mantenimiento)
                    .addComponent(txt_codigo_mantenimiento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt_tipo_mantenimiento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnl_controles_maquinariaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txt_id_operario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt_nombre_operario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_buscar_operario)
                    .addComponent(lbl_operario))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnl_controles_maquinariaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(dtc_fecha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbl_fecha))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnl_controles_maquinariaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnl_controles_maquinariaLayout.createSequentialGroup()
                        .addComponent(lbl_observaciones)
                        .addGap(0, 264, Short.MAX_VALUE))
                    .addComponent(jScrollPane_observaciones, javax.swing.GroupLayout.DEFAULT_SIZE, 281, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pnl_botones, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pnl_contenido.add(pnl_controles_maquinaria);

        pnl_tabla.setBackground(new java.awt.Color(255, 255, 255));

        lbl_buscar_area.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lbl_buscar_area.setText("Areas de trabajo:");

        cmb_areas.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cmb_areasItemStateChanged(evt);
            }
        });

        lbl_buscar_maquinaria.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lbl_buscar_maquinaria.setText("Máquinaria:");

        cmb_maquinarias.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cmb_maquinariasItemStateChanged(evt);
            }
        });

        tab_ejecuciones.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tab_ejecuciones.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tab_ejecucionesMouseClicked(evt);
            }
        });
        jScrollPane_tabla_ejecucion.setViewportView(tab_ejecuciones);

        lbl_num_registros.setText("Número de maquinarias:");

        lbl_fecha1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lbl_fecha1.setText("Desde:");

        dtc_fecha1.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                dtc_fecha1PropertyChange(evt);
            }
        });

        lbl_fecha2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lbl_fecha2.setText("Hasta:");

        dtc_fecha2.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                dtc_fecha2PropertyChange(evt);
            }
        });

        javax.swing.GroupLayout pnl_tablaLayout = new javax.swing.GroupLayout(pnl_tabla);
        pnl_tabla.setLayout(pnl_tablaLayout);
        pnl_tablaLayout.setHorizontalGroup(
            pnl_tablaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnl_tablaLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnl_tablaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jScrollPane_tabla_ejecucion)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, pnl_tablaLayout.createSequentialGroup()
                        .addComponent(lbl_buscar_area)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(cmb_areas, javax.swing.GroupLayout.PREFERRED_SIZE, 183, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(lbl_buscar_maquinaria)
                        .addGap(18, 18, 18)
                        .addComponent(cmb_maquinarias, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(pnl_tablaLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(lbl_num_registros))
                    .addGroup(pnl_tablaLayout.createSequentialGroup()
                        .addComponent(lbl_fecha1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(dtc_fecha1, javax.swing.GroupLayout.DEFAULT_SIZE, 244, Short.MAX_VALUE)
                        .addGap(18, 18, 18)
                        .addComponent(lbl_fecha2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(dtc_fecha2, javax.swing.GroupLayout.PREFERRED_SIZE, 256, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        pnl_tablaLayout.setVerticalGroup(
            pnl_tablaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnl_tablaLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnl_tablaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnl_tablaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(lbl_buscar_maquinaria)
                        .addComponent(cmb_maquinarias, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(pnl_tablaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(lbl_buscar_area)
                        .addComponent(cmb_areas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(pnl_tablaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(dtc_fecha2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbl_fecha2, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(dtc_fecha1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbl_fecha1, javax.swing.GroupLayout.Alignment.TRAILING))
                .addGap(11, 11, 11)
                .addComponent(jScrollPane_tabla_ejecucion, javax.swing.GroupLayout.DEFAULT_SIZE, 401, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lbl_num_registros)
                .addContainerGap())
        );

        pnl_contenido.add(pnl_tabla);

        getContentPane().add(pnl_contenido, java.awt.BorderLayout.CENTER);

        pnl_pie.setBackground(new java.awt.Color(82, 190, 128));
        pnl_pie.setPreferredSize(new java.awt.Dimension(1280, 40));
        pnl_pie.setLayout(new java.awt.BorderLayout());
        getContentPane().add(pnl_pie, java.awt.BorderLayout.SOUTH);

        setSize(new java.awt.Dimension(1296, 681));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btn_guardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_guardarActionPerformed
        //Validacion de datos
        if (txt_id_maquina.getText().equals("")) {
            JOptionPane.showMessageDialog(this, "Se debe seleccionar la maquina que se esta revisando");
            btn_buscar_maquina.requestFocus();
            return;
        }
        if (txt_id_mantenimiento.getText().equals("")) {
            JOptionPane.showMessageDialog(this, "Se debe seleccionar el mantenimiento a ejecutar");
            btn_buscar_mantenimiento.requestFocus();
            return;
        }
        if (txt_id_operario.getText().equals("") || txt_id_operario.getText().equals("0")) {
            JOptionPane.showMessageDialog(this, "Se debe seleccionar el operario que ejecutará el mantenimiento");
            btn_buscar_operario.requestFocus();
            return;
        }

        //Lectura de datos
        Ejecucion dts = new Ejecucion();
        dts.setId_maquina(Integer.parseInt(txt_id_maquina.getText()));
        dts.setId_mantenimiento(Integer.parseInt(txt_id_mantenimiento.getText()));
        dts.setId_operario(Integer.parseInt(txt_id_operario.getText()));
        dts.setFecha(Auxiliar.SQLDate(dtc_fecha.getCalendar()));
        dts.setObservaciones(txt_observaciones.getText());

        //¿Se está tratando de registrar una ejecución futura?
        Date fechaHoy = Auxiliar.SQLDate(Calendar.getInstance());
        if (dts.getFecha().compareTo(fechaHoy) > 0) {
            JOptionPane.showMessageDialog(this, "Por comodidad, no puede registrar ejecuciones futuras");
            return;
        }

        //Verificando si ya hay una ejecucion registrada con estos datos
        if (new ConsulEjecucion().haSidoRegistrada(dts)) {
            JOptionPane.showMessageDialog(this, "La ejecución que está tratando de guardar ya ha sido registrada antes");
            return;
        }

        //Envio de datos
        ConsulEjecucion func = new ConsulEjecucion();
        if (accion.equals("guardar")) {
            if (txt_tipo_mantenimiento.getText().equals("MP")) {//Si se está guardando una ejecución de un MP
                //Verificando si hay una agenda iniciada y una fecha agendada para la ejecucion
                String[] verificacion = new ConsulAgenda().verificar(dts);
                switch (verificacion[0]) {
                    case "sinAgenda":
                        String msg1 = "Esta ejecución no tiene una agenda iniciada\n"
                                + "¿Desea crear una agenda para esta ejecución?";
                        int confirmacion1 = JOptionPane.showConfirmDialog(this, msg1, "Confirmar", 2);
                        if (confirmacion1 == 0) {
                            //Lectura de datos (agenda)
                            Agenda dts2 = new Agenda();
                            dts2.setId_maquina(dts.getId_maquina());
                            dts2.setId_mant_prev(dts.getId_mantenimiento());
                            dts2.setFecha_inicio(dts.getFecha());
                            dts2.setEstado("Iniciado");
                            //Envio de datos (agenda)
                            if (new ConsulAgenda().insertar(dts2)) {
                                JOptionPane.showMessageDialog(this, "Agenda registrada satisfactoriamente");
                                Mostrar();
                                Inhabilitar();
                            }
                            //Envio de datos (ejecucion)
                            if (func.insertar(dts)) {
                                JOptionPane.showMessageDialog(this, "Ejecución registrada satisfactoriamente");
                                Mostrar();
                                Inhabilitar();
                            }
                        } else {
                            return;
                        }
                        break;
                    case "conAgendaNoIniciada":
                        String msg2 = "Esta ejecución tiene una agenda no iniciada\n"
                                + "¿Desea iniciar esta agenda con la fecha de esta ejecución como fecha de inicio?";
                        int confirmacion2 = JOptionPane.showConfirmDialog(this, msg2, "Confirmar", 2);
                        if (confirmacion2 == 0) {
                            //Inicializacion de agenda
                            int idAgenda = Integer.parseInt(verificacion[1]);
                            if (new ConsulAgenda().iniciar(idAgenda, dts.getFecha())) {
                                JOptionPane.showMessageDialog(this, "Agenda iniciada satisfactoriamente");
                            }
                            //Envio de datos (ejecucion)
                            if (func.insertar(dts)) {
                                JOptionPane.showMessageDialog(this, "Ejecución registrada satisfactoriamente");
                                Mostrar();
                                Inhabilitar();
                            }
                        } else {
                            return;
                        }
                        break;
                    case "sinFecha":
                        JOptionPane.showMessageDialog(this, "No hay una fecha valida en la agenda de esta ejecución");
                        return;
                    case "conFecha":
                        if (func.insertar(dts)) {
                            JOptionPane.showMessageDialog(this, "Ejecución registrada satisfactoriamente");
                            Mostrar();
                            Inhabilitar();
                        }
                        break;
                    default:
                        JOptionPane.showMessageDialog(this, "Error al verificar agenda de esta ejecución");
                }
            } else if (txt_tipo_mantenimiento.getText().equals("MC")) {//Si se está guardando una ejecución de un MC
                if (func.insertar(dts)) {
                    JOptionPane.showMessageDialog(this, "Ejecución registrada satisfactoriamente");
                    Mostrar();
                    Inhabilitar();
                }
            }

        } else if (accion.equals("editar")) {
            dts.setId(Integer.parseInt(txt_id_ejecucion.getText()));
            if (func.editar(dts)) {
                JOptionPane.showMessageDialog(this, "Ejecución editada satisfactoriamente");
                Mostrar();
                Inhabilitar();
            }
        }

        //Lo llamo la tabla de pendientes
        if (pendiente) {
            frm_menu_principal.Mostrar();
            pendiente = false;
            this.dispose();
        }
    }//GEN-LAST:event_btn_guardarActionPerformed

    private void btn_eliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_eliminarActionPerformed
        if (!txt_id_ejecucion.getText().equals("")) {
            int confirmacion = JOptionPane.showConfirmDialog(this, "¿Estás seguro de eliminar la ejecución?", "Confirmar", 2);
            if (confirmacion == 0) {
                //Lectura de datos
                Ejecucion dts = new Ejecucion();
                dts.setId(Integer.parseInt(txt_id_ejecucion.getText()));
                //Envio de datos
                ConsulEjecucion func = new ConsulEjecucion();
                if (func.eliminar(dts)) {
                    JOptionPane.showMessageDialog(this, "Ejecución eliminada satisfactoriamente");
                    Mostrar();
                    Inhabilitar();
                }
            }
        }
    }//GEN-LAST:event_btn_eliminarActionPerformed

    private void btn_buscar_mantenimientoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_buscar_mantenimientoActionPerformed
        if (txt_id_maquina.getText().equals("")) {
            JOptionPane.showMessageDialog(rootPane, "Primero seleccione una maquina");
            btn_buscar_maquina.requestFocus();
        } else {
            frm_buscar_mantenimiento.id_maquina = txt_id_maquina.getText();
            frm_buscar_mantenimiento.destino = "EJ";
            frm_buscar_mantenimiento form = new frm_buscar_mantenimiento();
            form.toFront();
            form.setVisible(true);
        }
    }//GEN-LAST:event_btn_buscar_mantenimientoActionPerformed

    private void btn_nuevoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_nuevoActionPerformed
        Habilitar();
        btn_guardar.setText("Guardar");
        accion = "guardar";
        pendiente = false;
    }//GEN-LAST:event_btn_nuevoActionPerformed

    private void cmb_areasItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cmb_areasItemStateChanged
        ListaMaquinarias();
        Mostrar();
    }//GEN-LAST:event_cmb_areasItemStateChanged

    private void tab_ejecucionesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tab_ejecucionesMouseClicked

        //Habilitacion de campos de maquinaria
        Inhabilitar();
        btn_guardar.setText("Editar");
        Habilitar();
        btn_eliminar.setEnabled(true);
        accion = "editar";
        pendiente = false;
        //Rellenado de campos maquinaria
        int fila = tab_ejecuciones.rowAtPoint(evt.getPoint());
        txt_id_ejecucion.setText(tab_ejecuciones.getValueAt(fila, 0).toString());
        txt_id_maquina.setText(tab_ejecuciones.getValueAt(fila, 1).toString());
        txt_codigo_maquina.setText(tab_ejecuciones.getValueAt(fila, 2).toString());
        txt_id_mantenimiento.setText(tab_ejecuciones.getValueAt(fila, 3).toString());
        txt_codigo_mantenimiento.setText(tab_ejecuciones.getValueAt(fila, 4).toString());
        txt_nombre_mantenimiento.setText(tab_ejecuciones.getValueAt(fila, 5).toString());
        txt_tipo_mantenimiento.setText(tab_ejecuciones.getValueAt(fila, 6).toString());
        txt_id_operario.setText(tab_ejecuciones.getValueAt(fila, 7).toString());
        txt_nombre_operario.setText(tab_ejecuciones.getValueAt(fila, 8).toString());
        dtc_fecha.setDate(Date.valueOf(tab_ejecuciones.getValueAt(fila, 9).toString()));
        txt_observaciones.setText(tab_ejecuciones.getValueAt(fila, 10).toString());
        if (txt_tipo_mantenimiento.getText().equals("MP")) {
            dtc_fecha.setEnabled(false);
            btn_buscar_maquina.setEnabled(false);
            btn_buscar_mantenimiento.setEnabled(false);
        }

    }//GEN-LAST:event_tab_ejecucionesMouseClicked

    private void formWindowClosed(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosed

        if (ventana.equals("MENU")) {//Si lo abrió el menu principal

        }

    }//GEN-LAST:event_formWindowClosed

    private void btn_buscar_operarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_buscar_operarioActionPerformed
        new frm_buscar_operarios().setVisible(true);
    }//GEN-LAST:event_btn_buscar_operarioActionPerformed

    private void cmb_maquinariasItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cmb_maquinariasItemStateChanged
        Mostrar();
    }//GEN-LAST:event_cmb_maquinariasItemStateChanged

    private void btn_buscar_maquinaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_buscar_maquinaActionPerformed
        frm_buscar_maquina.destino = "EJ";
        frm_buscar_maquina form = new frm_buscar_maquina();
        form.toFront();
        form.setVisible(true);
    }//GEN-LAST:event_btn_buscar_maquinaActionPerformed

    private void dtc_fecha1PropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_dtc_fecha1PropertyChange
        if ("date".equals(evt.getPropertyName()) && dtc_fecha2.getCalendar() != null) {
            Mostrar();
        }
    }//GEN-LAST:event_dtc_fecha1PropertyChange

    private void dtc_fecha2PropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_dtc_fecha2PropertyChange
        if ("date".equals(evt.getPropertyName()) && dtc_fecha1.getCalendar() != null) {
            Mostrar();
        }
    }//GEN-LAST:event_dtc_fecha2PropertyChange

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frm_ejecucion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frm_ejecucion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frm_ejecucion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frm_ejecucion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frm_ejecucion().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public static javax.swing.JButton btn_buscar_mantenimiento;
    public static javax.swing.JButton btn_buscar_maquina;
    private static javax.swing.JButton btn_buscar_operario;
    private static javax.swing.JButton btn_eliminar;
    public static javax.swing.JButton btn_guardar;
    private javax.swing.JButton btn_nuevo;
    public static javax.swing.JComboBox<String> cmb_areas;
    public static javax.swing.JComboBox<String> cmb_maquinarias;
    public static com.toedter.calendar.JDateChooser dtc_fecha;
    private static com.toedter.calendar.JDateChooser dtc_fecha1;
    private static com.toedter.calendar.JDateChooser dtc_fecha2;
    private javax.swing.JScrollPane jScrollPane_observaciones;
    private javax.swing.JScrollPane jScrollPane_tabla_ejecucion;
    private javax.swing.JLabel lbl_buscar_area;
    private javax.swing.JLabel lbl_buscar_maquinaria;
    private javax.swing.JLabel lbl_fecha;
    private javax.swing.JLabel lbl_fecha1;
    private javax.swing.JLabel lbl_fecha2;
    private javax.swing.JLabel lbl_mantenimiento;
    private javax.swing.JLabel lbl_maquina;
    private static javax.swing.JLabel lbl_num_registros;
    private javax.swing.JLabel lbl_observaciones;
    private javax.swing.JLabel lbl_operario;
    private javax.swing.JLabel lbl_titulo;
    private javax.swing.JPanel pnl_botones;
    private javax.swing.JPanel pnl_cabecera;
    private javax.swing.JPanel pnl_contenido;
    private javax.swing.JPanel pnl_controles_maquinaria;
    private javax.swing.JPanel pnl_pie;
    private javax.swing.JPanel pnl_sesion_info;
    private javax.swing.JPanel pnl_tabla;
    private static javax.swing.JTable tab_ejecuciones;
    public static javax.swing.JTextField txt_codigo_mantenimiento;
    public static javax.swing.JTextField txt_codigo_maquina;
    private static javax.swing.JTextField txt_id_ejecucion;
    public static javax.swing.JTextField txt_id_mantenimiento;
    public static javax.swing.JTextField txt_id_maquina;
    public static javax.swing.JTextField txt_id_operario;
    public static javax.swing.JTextField txt_nombre_mantenimiento;
    public static javax.swing.JTextField txt_nombre_operario;
    private static javax.swing.JTextArea txt_observaciones;
    public static javax.swing.JTextField txt_tipo_mantenimiento;
    // End of variables declaration//GEN-END:variables
}
